/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
)

// checks if the InputUpdateAttachment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputUpdateAttachment{}

// InputUpdateAttachment struct for InputUpdateAttachment
type InputUpdateAttachment struct {
	External *bool `json:"external,omitempty"`
}

// NewInputUpdateAttachment instantiates a new InputUpdateAttachment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputUpdateAttachment() *InputUpdateAttachment {
	this := InputUpdateAttachment{}
	return &this
}

// NewInputUpdateAttachmentWithDefaults instantiates a new InputUpdateAttachment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputUpdateAttachmentWithDefaults() *InputUpdateAttachment {
	this := InputUpdateAttachment{}
	return &this
}

// GetExternal returns the External field value if set, zero value otherwise.
func (o *InputUpdateAttachment) GetExternal() bool {
	if o == nil || IsNil(o.External) {
		var ret bool
		return ret
	}
	return *o.External
}

// GetExternalOk returns a tuple with the External field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputUpdateAttachment) GetExternalOk() (*bool, bool) {
	if o == nil || IsNil(o.External) {
		return nil, false
	}
	return o.External, true
}

// HasExternal returns a boolean if a field has been set.
func (o *InputUpdateAttachment) HasExternal() bool {
	if o != nil && !IsNil(o.External) {
		return true
	}

	return false
}

// SetExternal gets a reference to the given bool and assigns it to the External field.
func (o *InputUpdateAttachment) SetExternal(v bool) {
	o.External = &v
}

func (o InputUpdateAttachment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputUpdateAttachment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.External) {
		toSerialize["external"] = o.External
	}
	return toSerialize, nil
}

type NullableInputUpdateAttachment struct {
	value *InputUpdateAttachment
	isSet bool
}

func (v NullableInputUpdateAttachment) Get() *InputUpdateAttachment {
	return v.value
}

func (v *NullableInputUpdateAttachment) Set(val *InputUpdateAttachment) {
	v.value = val
	v.isSet = true
}

func (v NullableInputUpdateAttachment) IsSet() bool {
	return v.isSet
}

func (v *NullableInputUpdateAttachment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputUpdateAttachment(val *InputUpdateAttachment) *NullableInputUpdateAttachment {
	return &NullableInputUpdateAttachment{value: val, isSet: true}
}

func (v NullableInputUpdateAttachment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputUpdateAttachment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


