/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Gt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Gt{}

// Gt struct for Gt
type Gt struct {
	Gt FieldValue `json:"_gt"`
}

type _Gt Gt

// NewGt instantiates a new Gt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGt(gt FieldValue) *Gt {
	this := Gt{}
	this.Gt = gt
	return &this
}

// NewGtWithDefaults instantiates a new Gt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGtWithDefaults() *Gt {
	this := Gt{}
	return &this
}

// GetGt returns the Gt field value
func (o *Gt) GetGt() FieldValue {
	if o == nil {
		var ret FieldValue
		return ret
	}

	return o.Gt
}

// GetGtOk returns a tuple with the Gt field value
// and a boolean to check if the value has been set.
func (o *Gt) GetGtOk() (*FieldValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gt, true
}

// SetGt sets field value
func (o *Gt) SetGt(v FieldValue) {
	o.Gt = v
}

func (o Gt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Gt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_gt"] = o.Gt
	return toSerialize, nil
}

func (o *Gt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_gt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGt := _Gt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGt)

	if err != nil {
		return err
	}

	*o = Gt(varGt)

	return err
}

type NullableGt struct {
	value *Gt
	isSet bool
}

func (v NullableGt) Get() *Gt {
	return v.value
}

func (v *NullableGt) Set(val *Gt) {
	v.value = val
	v.isSet = true
}

func (v NullableGt) IsSet() bool {
	return v.isSet
}

func (v *NullableGt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGt(val *Gt) *NullableGt {
	return &NullableGt{value: val, isSet: true}
}

func (v NullableGt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


