/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ```

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ObservableTable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObservableTable{}

// ObservableTable struct for ObservableTable
type ObservableTable struct {
	Title       *string              `json:"title,omitempty"`
	Columns     []ObservableField    `json:"columns,omitempty"`
	Filter      *Filter              `json:"filter,omitempty"`
	Sort        []AlertListSortInner `json:"sort,omitempty"`
	ProtectData bool                 `json:"protectData"`
	MaxElements *int32               `json:"maxElements,omitempty"`
	Kind        Kind                 `json:"_kind"`
}

type _ObservableTable ObservableTable

// NewObservableTable instantiates a new ObservableTable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObservableTable(protectData bool, kind Kind) *ObservableTable {
	this := ObservableTable{}
	this.ProtectData = protectData
	this.Kind = kind
	return &this
}

// NewObservableTableWithDefaults instantiates a new ObservableTable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObservableTableWithDefaults() *ObservableTable {
	this := ObservableTable{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ObservableTable) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObservableTable) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ObservableTable) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ObservableTable) SetTitle(v string) {
	o.Title = &v
}

// GetColumns returns the Columns field value if set, zero value otherwise.
func (o *ObservableTable) GetColumns() []ObservableField {
	if o == nil || IsNil(o.Columns) {
		var ret []ObservableField
		return ret
	}
	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObservableTable) GetColumnsOk() ([]ObservableField, bool) {
	if o == nil || IsNil(o.Columns) {
		return nil, false
	}
	return o.Columns, true
}

// HasColumns returns a boolean if a field has been set.
func (o *ObservableTable) HasColumns() bool {
	if o != nil && !IsNil(o.Columns) {
		return true
	}

	return false
}

// SetColumns gets a reference to the given []ObservableField and assigns it to the Columns field.
func (o *ObservableTable) SetColumns(v []ObservableField) {
	o.Columns = v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *ObservableTable) GetFilter() Filter {
	if o == nil || IsNil(o.Filter) {
		var ret Filter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObservableTable) GetFilterOk() (*Filter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *ObservableTable) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given Filter and assigns it to the Filter field.
func (o *ObservableTable) SetFilter(v Filter) {
	o.Filter = &v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *ObservableTable) GetSort() []AlertListSortInner {
	if o == nil || IsNil(o.Sort) {
		var ret []AlertListSortInner
		return ret
	}
	return o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObservableTable) GetSortOk() ([]AlertListSortInner, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *ObservableTable) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given []AlertListSortInner and assigns it to the Sort field.
func (o *ObservableTable) SetSort(v []AlertListSortInner) {
	o.Sort = v
}

// GetProtectData returns the ProtectData field value
func (o *ObservableTable) GetProtectData() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ProtectData
}

// GetProtectDataOk returns a tuple with the ProtectData field value
// and a boolean to check if the value has been set.
func (o *ObservableTable) GetProtectDataOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProtectData, true
}

// SetProtectData sets field value
func (o *ObservableTable) SetProtectData(v bool) {
	o.ProtectData = v
}

// GetMaxElements returns the MaxElements field value if set, zero value otherwise.
func (o *ObservableTable) GetMaxElements() int32 {
	if o == nil || IsNil(o.MaxElements) {
		var ret int32
		return ret
	}
	return *o.MaxElements
}

// GetMaxElementsOk returns a tuple with the MaxElements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObservableTable) GetMaxElementsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxElements) {
		return nil, false
	}
	return o.MaxElements, true
}

// HasMaxElements returns a boolean if a field has been set.
func (o *ObservableTable) HasMaxElements() bool {
	if o != nil && !IsNil(o.MaxElements) {
		return true
	}

	return false
}

// SetMaxElements gets a reference to the given int32 and assigns it to the MaxElements field.
func (o *ObservableTable) SetMaxElements(v int32) {
	o.MaxElements = &v
}

// GetKind returns the Kind field value
func (o *ObservableTable) GetKind() Kind {
	if o == nil {
		var ret Kind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ObservableTable) GetKindOk() (*Kind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ObservableTable) SetKind(v Kind) {
	o.Kind = v
}

func (o ObservableTable) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObservableTable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Columns) {
		toSerialize["columns"] = o.Columns
	}
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}
	toSerialize["protectData"] = o.ProtectData
	if !IsNil(o.MaxElements) {
		toSerialize["maxElements"] = o.MaxElements
	}
	toSerialize["_kind"] = o.Kind
	return toSerialize, nil
}

func (o *ObservableTable) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"protectData",
		"_kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObservableTable := _ObservableTable{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varObservableTable)

	if err != nil {
		return err
	}

	*o = ObservableTable(varObservableTable)

	return err
}

type NullableObservableTable struct {
	value *ObservableTable
	isSet bool
}

func (v NullableObservableTable) Get() *ObservableTable {
	return v.value
}

func (v *NullableObservableTable) Set(val *ObservableTable) {
	v.value = val
	v.isSet = true
}

func (v NullableObservableTable) IsSet() bool {
	return v.isSet
}

func (v *NullableObservableTable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObservableTable(val *ObservableTable) *NullableObservableTable {
	return &NullableObservableTable{value: val, isSet: true}
}

func (v NullableObservableTable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObservableTable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
