/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ```

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// OutputEmailIntakeMailbox - struct for OutputEmailIntakeMailbox
type OutputEmailIntakeMailbox struct {
	OutputEmailIntakeApiMailbox  *OutputEmailIntakeApiMailbox
	OutputEmailIntakeImapMailbox *OutputEmailIntakeImapMailbox
}

// OutputEmailIntakeApiMailboxAsOutputEmailIntakeMailbox is a convenience function that returns OutputEmailIntakeApiMailbox wrapped in OutputEmailIntakeMailbox
func OutputEmailIntakeApiMailboxAsOutputEmailIntakeMailbox(v *OutputEmailIntakeApiMailbox) OutputEmailIntakeMailbox {
	return OutputEmailIntakeMailbox{
		OutputEmailIntakeApiMailbox: v,
	}
}

// OutputEmailIntakeImapMailboxAsOutputEmailIntakeMailbox is a convenience function that returns OutputEmailIntakeImapMailbox wrapped in OutputEmailIntakeMailbox
func OutputEmailIntakeImapMailboxAsOutputEmailIntakeMailbox(v *OutputEmailIntakeImapMailbox) OutputEmailIntakeMailbox {
	return OutputEmailIntakeMailbox{
		OutputEmailIntakeImapMailbox: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *OutputEmailIntakeMailbox) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into OutputEmailIntakeApiMailbox
	err = newStrictDecoder(data).Decode(&dst.OutputEmailIntakeApiMailbox)
	if err == nil {
		jsonOutputEmailIntakeApiMailbox, _ := json.Marshal(dst.OutputEmailIntakeApiMailbox)
		if string(jsonOutputEmailIntakeApiMailbox) == "{}" { // empty struct
			dst.OutputEmailIntakeApiMailbox = nil
		} else {
			if err = validator.Validate(dst.OutputEmailIntakeApiMailbox); err != nil {
				dst.OutputEmailIntakeApiMailbox = nil
			} else {
				match++
			}
		}
	} else {
		dst.OutputEmailIntakeApiMailbox = nil
	}

	// try to unmarshal data into OutputEmailIntakeImapMailbox
	err = newStrictDecoder(data).Decode(&dst.OutputEmailIntakeImapMailbox)
	if err == nil {
		jsonOutputEmailIntakeImapMailbox, _ := json.Marshal(dst.OutputEmailIntakeImapMailbox)
		if string(jsonOutputEmailIntakeImapMailbox) == "{}" { // empty struct
			dst.OutputEmailIntakeImapMailbox = nil
		} else {
			if err = validator.Validate(dst.OutputEmailIntakeImapMailbox); err != nil {
				dst.OutputEmailIntakeImapMailbox = nil
			} else {
				match++
			}
		}
	} else {
		dst.OutputEmailIntakeImapMailbox = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.OutputEmailIntakeApiMailbox = nil
		dst.OutputEmailIntakeImapMailbox = nil

		return fmt.Errorf("data matches more than one schema in oneOf(OutputEmailIntakeMailbox)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(OutputEmailIntakeMailbox)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src OutputEmailIntakeMailbox) MarshalJSON() ([]byte, error) {
	if src.OutputEmailIntakeApiMailbox != nil {
		return json.Marshal(&src.OutputEmailIntakeApiMailbox)
	}

	if src.OutputEmailIntakeImapMailbox != nil {
		return json.Marshal(&src.OutputEmailIntakeImapMailbox)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *OutputEmailIntakeMailbox) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.OutputEmailIntakeApiMailbox != nil {
		return obj.OutputEmailIntakeApiMailbox
	}

	if obj.OutputEmailIntakeImapMailbox != nil {
		return obj.OutputEmailIntakeImapMailbox
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj OutputEmailIntakeMailbox) GetActualInstanceValue() interface{} {
	if obj.OutputEmailIntakeApiMailbox != nil {
		return *obj.OutputEmailIntakeApiMailbox
	}

	if obj.OutputEmailIntakeImapMailbox != nil {
		return *obj.OutputEmailIntakeImapMailbox
	}

	// all schemas are nil
	return nil
}

type NullableOutputEmailIntakeMailbox struct {
	value *OutputEmailIntakeMailbox
	isSet bool
}

func (v NullableOutputEmailIntakeMailbox) Get() *OutputEmailIntakeMailbox {
	return v.value
}

func (v *NullableOutputEmailIntakeMailbox) Set(val *OutputEmailIntakeMailbox) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputEmailIntakeMailbox) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputEmailIntakeMailbox) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputEmailIntakeMailbox(val *OutputEmailIntakeMailbox) *NullableOutputEmailIntakeMailbox {
	return &NullableOutputEmailIntakeMailbox{value: val, isSet: true}
}

func (v NullableOutputEmailIntakeMailbox) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputEmailIntakeMailbox) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
