/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InputQueryPagingOperation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputQueryPagingOperation{}

// InputQueryPagingOperation struct for InputQueryPagingOperation
type InputQueryPagingOperation struct {
	ExtraData []string `json:"extraData,omitempty"`
	From int32 `json:"from"`
	To int32 `json:"to"`
	Name string `json:"_name"`
}

type _InputQueryPagingOperation InputQueryPagingOperation

// NewInputQueryPagingOperation instantiates a new InputQueryPagingOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputQueryPagingOperation(from int32, to int32, name string) *InputQueryPagingOperation {
	this := InputQueryPagingOperation{}
	this.From = from
	this.To = to
	this.Name = name
	return &this
}

// NewInputQueryPagingOperationWithDefaults instantiates a new InputQueryPagingOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputQueryPagingOperationWithDefaults() *InputQueryPagingOperation {
	this := InputQueryPagingOperation{}
	return &this
}

// GetExtraData returns the ExtraData field value if set, zero value otherwise.
func (o *InputQueryPagingOperation) GetExtraData() []string {
	if o == nil || IsNil(o.ExtraData) {
		var ret []string
		return ret
	}
	return o.ExtraData
}

// GetExtraDataOk returns a tuple with the ExtraData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputQueryPagingOperation) GetExtraDataOk() ([]string, bool) {
	if o == nil || IsNil(o.ExtraData) {
		return nil, false
	}
	return o.ExtraData, true
}

// HasExtraData returns a boolean if a field has been set.
func (o *InputQueryPagingOperation) HasExtraData() bool {
	if o != nil && !IsNil(o.ExtraData) {
		return true
	}

	return false
}

// SetExtraData gets a reference to the given []string and assigns it to the ExtraData field.
func (o *InputQueryPagingOperation) SetExtraData(v []string) {
	o.ExtraData = v
}

// GetFrom returns the From field value
func (o *InputQueryPagingOperation) GetFrom() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *InputQueryPagingOperation) GetFromOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *InputQueryPagingOperation) SetFrom(v int32) {
	o.From = v
}

// GetTo returns the To field value
func (o *InputQueryPagingOperation) GetTo() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *InputQueryPagingOperation) GetToOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *InputQueryPagingOperation) SetTo(v int32) {
	o.To = v
}

// GetName returns the Name field value
func (o *InputQueryPagingOperation) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InputQueryPagingOperation) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InputQueryPagingOperation) SetName(v string) {
	o.Name = v
}

func (o InputQueryPagingOperation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputQueryPagingOperation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExtraData) {
		toSerialize["extraData"] = o.ExtraData
	}
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	toSerialize["_name"] = o.Name
	return toSerialize, nil
}

func (o *InputQueryPagingOperation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from",
		"to",
		"_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputQueryPagingOperation := _InputQueryPagingOperation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputQueryPagingOperation)

	if err != nil {
		return err
	}

	*o = InputQueryPagingOperation(varInputQueryPagingOperation)

	return err
}

type NullableInputQueryPagingOperation struct {
	value *InputQueryPagingOperation
	isSet bool
}

func (v NullableInputQueryPagingOperation) Get() *InputQueryPagingOperation {
	return v.value
}

func (v *NullableInputQueryPagingOperation) Set(val *InputQueryPagingOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableInputQueryPagingOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableInputQueryPagingOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputQueryPagingOperation(val *InputQueryPagingOperation) *NullableInputQueryPagingOperation {
	return &NullableInputQueryPagingOperation{value: val, isSet: true}
}

func (v NullableInputQueryPagingOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputQueryPagingOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


