/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ```

API version: v1-5.5.11-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OutputPublicStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputPublicStatus{}

// OutputPublicStatus struct for OutputPublicStatus
type OutputPublicStatus struct {
	Sso          bool                `json:"sso"`
	SsoProviders []OutputSsoProvider `json:"ssoProviders,omitempty"`
	Version      string              `json:"version"`
}

type _OutputPublicStatus OutputPublicStatus

// NewOutputPublicStatus instantiates a new OutputPublicStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputPublicStatus(sso bool, version string) *OutputPublicStatus {
	this := OutputPublicStatus{}
	this.Sso = sso
	this.Version = version
	return &this
}

// NewOutputPublicStatusWithDefaults instantiates a new OutputPublicStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputPublicStatusWithDefaults() *OutputPublicStatus {
	this := OutputPublicStatus{}
	return &this
}

// GetSso returns the Sso field value
func (o *OutputPublicStatus) GetSso() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Sso
}

// GetSsoOk returns a tuple with the Sso field value
// and a boolean to check if the value has been set.
func (o *OutputPublicStatus) GetSsoOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sso, true
}

// SetSso sets field value
func (o *OutputPublicStatus) SetSso(v bool) {
	o.Sso = v
}

// GetSsoProviders returns the SsoProviders field value if set, zero value otherwise.
func (o *OutputPublicStatus) GetSsoProviders() []OutputSsoProvider {
	if o == nil || IsNil(o.SsoProviders) {
		var ret []OutputSsoProvider
		return ret
	}
	return o.SsoProviders
}

// GetSsoProvidersOk returns a tuple with the SsoProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputPublicStatus) GetSsoProvidersOk() ([]OutputSsoProvider, bool) {
	if o == nil || IsNil(o.SsoProviders) {
		return nil, false
	}
	return o.SsoProviders, true
}

// HasSsoProviders returns a boolean if a field has been set.
func (o *OutputPublicStatus) HasSsoProviders() bool {
	if o != nil && !IsNil(o.SsoProviders) {
		return true
	}

	return false
}

// SetSsoProviders gets a reference to the given []OutputSsoProvider and assigns it to the SsoProviders field.
func (o *OutputPublicStatus) SetSsoProviders(v []OutputSsoProvider) {
	o.SsoProviders = v
}

// GetVersion returns the Version field value
func (o *OutputPublicStatus) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *OutputPublicStatus) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *OutputPublicStatus) SetVersion(v string) {
	o.Version = v
}

func (o OutputPublicStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputPublicStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sso"] = o.Sso
	if !IsNil(o.SsoProviders) {
		toSerialize["ssoProviders"] = o.SsoProviders
	}
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *OutputPublicStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sso",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputPublicStatus := _OutputPublicStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputPublicStatus)

	if err != nil {
		return err
	}

	*o = OutputPublicStatus(varOutputPublicStatus)

	return err
}

type NullableOutputPublicStatus struct {
	value *OutputPublicStatus
	isSet bool
}

func (v NullableOutputPublicStatus) Get() *OutputPublicStatus {
	return v.value
}

func (v *NullableOutputPublicStatus) Set(val *OutputPublicStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputPublicStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputPublicStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputPublicStatus(val *OutputPublicStatus) *NullableOutputPublicStatus {
	return &NullableOutputPublicStatus{value: val, isSet: true}
}

func (v NullableOutputPublicStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputPublicStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
