/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginInput{}

// LoginInput struct for LoginInput
type LoginInput struct {
	User string `json:"user"`
	Password string `json:"password"`
	// Organisation id or name to logged into
	Organisation *string `json:"organisation,omitempty"`
	Code *string `json:"code,omitempty"`
}

type _LoginInput LoginInput

// NewLoginInput instantiates a new LoginInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginInput(user string, password string) *LoginInput {
	this := LoginInput{}
	this.User = user
	this.Password = password
	var organisation string = "Uses user default organisation or first joined organisation"
	this.Organisation = &organisation
	return &this
}

// NewLoginInputWithDefaults instantiates a new LoginInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginInputWithDefaults() *LoginInput {
	this := LoginInput{}
	var organisation string = "Uses user default organisation or first joined organisation"
	this.Organisation = &organisation
	return &this
}

// GetUser returns the User field value
func (o *LoginInput) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *LoginInput) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *LoginInput) SetUser(v string) {
	o.User = v
}

// GetPassword returns the Password field value
func (o *LoginInput) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *LoginInput) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *LoginInput) SetPassword(v string) {
	o.Password = v
}

// GetOrganisation returns the Organisation field value if set, zero value otherwise.
func (o *LoginInput) GetOrganisation() string {
	if o == nil || IsNil(o.Organisation) {
		var ret string
		return ret
	}
	return *o.Organisation
}

// GetOrganisationOk returns a tuple with the Organisation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginInput) GetOrganisationOk() (*string, bool) {
	if o == nil || IsNil(o.Organisation) {
		return nil, false
	}
	return o.Organisation, true
}

// HasOrganisation returns a boolean if a field has been set.
func (o *LoginInput) HasOrganisation() bool {
	if o != nil && !IsNil(o.Organisation) {
		return true
	}

	return false
}

// SetOrganisation gets a reference to the given string and assigns it to the Organisation field.
func (o *LoginInput) SetOrganisation(v string) {
	o.Organisation = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *LoginInput) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginInput) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *LoginInput) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *LoginInput) SetCode(v string) {
	o.Code = &v
}

func (o LoginInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user"] = o.User
	toSerialize["password"] = o.Password
	if !IsNil(o.Organisation) {
		toSerialize["organisation"] = o.Organisation
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

func (o *LoginInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginInput := _LoginInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginInput)

	if err != nil {
		return err
	}

	*o = LoginInput(varLoginInput)

	return err
}

type NullableLoginInput struct {
	value *LoginInput
	isSet bool
}

func (v NullableLoginInput) Get() *LoginInput {
	return v.value
}

func (v *NullableLoginInput) Set(val *LoginInput) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginInput) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginInput(val *LoginInput) *NullableLoginInput {
	return &NullableLoginInput{value: val, isSet: true}
}

func (v NullableLoginInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


