/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputOrganisationLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputOrganisationLink{}

// OutputOrganisationLink struct for OutputOrganisationLink
type OutputOrganisationLink struct {
	LinkType string `json:"linkType"`
	OtherLinkType string `json:"otherLinkType"`
	Organisation OutputOrganisation `json:"organisation"`
}

type _OutputOrganisationLink OutputOrganisationLink

// NewOutputOrganisationLink instantiates a new OutputOrganisationLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputOrganisationLink(linkType string, otherLinkType string, organisation OutputOrganisation) *OutputOrganisationLink {
	this := OutputOrganisationLink{}
	this.LinkType = linkType
	this.OtherLinkType = otherLinkType
	this.Organisation = organisation
	return &this
}

// NewOutputOrganisationLinkWithDefaults instantiates a new OutputOrganisationLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputOrganisationLinkWithDefaults() *OutputOrganisationLink {
	this := OutputOrganisationLink{}
	return &this
}

// GetLinkType returns the LinkType field value
func (o *OutputOrganisationLink) GetLinkType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LinkType
}

// GetLinkTypeOk returns a tuple with the LinkType field value
// and a boolean to check if the value has been set.
func (o *OutputOrganisationLink) GetLinkTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LinkType, true
}

// SetLinkType sets field value
func (o *OutputOrganisationLink) SetLinkType(v string) {
	o.LinkType = v
}

// GetOtherLinkType returns the OtherLinkType field value
func (o *OutputOrganisationLink) GetOtherLinkType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OtherLinkType
}

// GetOtherLinkTypeOk returns a tuple with the OtherLinkType field value
// and a boolean to check if the value has been set.
func (o *OutputOrganisationLink) GetOtherLinkTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtherLinkType, true
}

// SetOtherLinkType sets field value
func (o *OutputOrganisationLink) SetOtherLinkType(v string) {
	o.OtherLinkType = v
}

// GetOrganisation returns the Organisation field value
func (o *OutputOrganisationLink) GetOrganisation() OutputOrganisation {
	if o == nil {
		var ret OutputOrganisation
		return ret
	}

	return o.Organisation
}

// GetOrganisationOk returns a tuple with the Organisation field value
// and a boolean to check if the value has been set.
func (o *OutputOrganisationLink) GetOrganisationOk() (*OutputOrganisation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organisation, true
}

// SetOrganisation sets field value
func (o *OutputOrganisationLink) SetOrganisation(v OutputOrganisation) {
	o.Organisation = v
}

func (o OutputOrganisationLink) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputOrganisationLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["linkType"] = o.LinkType
	toSerialize["otherLinkType"] = o.OtherLinkType
	toSerialize["organisation"] = o.Organisation
	return toSerialize, nil
}

func (o *OutputOrganisationLink) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"linkType",
		"otherLinkType",
		"organisation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputOrganisationLink := _OutputOrganisationLink{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputOrganisationLink)

	if err != nil {
		return err
	}

	*o = OutputOrganisationLink(varOutputOrganisationLink)

	return err
}

type NullableOutputOrganisationLink struct {
	value *OutputOrganisationLink
	isSet bool
}

func (v NullableOutputOrganisationLink) Get() *OutputOrganisationLink {
	return v.value
}

func (v *NullableOutputOrganisationLink) Set(val *OutputOrganisationLink) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputOrganisationLink) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputOrganisationLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputOrganisationLink(val *OutputOrganisationLink) *NullableOutputOrganisationLink {
	return &NullableOutputOrganisationLink{value: val, isSet: true}
}

func (v NullableOutputOrganisationLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputOrganisationLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


