/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FieldValues type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FieldValues{}

// FieldValues struct for FieldValues
type FieldValues struct {
	Field string `json:"_field"`
	Values []interface{} `json:"_values,omitempty"`
}

type _FieldValues FieldValues

// NewFieldValues instantiates a new FieldValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFieldValues(field string) *FieldValues {
	this := FieldValues{}
	this.Field = field
	return &this
}

// NewFieldValuesWithDefaults instantiates a new FieldValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFieldValuesWithDefaults() *FieldValues {
	this := FieldValues{}
	return &this
}

// GetField returns the Field field value
func (o *FieldValues) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *FieldValues) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *FieldValues) SetField(v string) {
	o.Field = v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *FieldValues) GetValues() []interface{} {
	if o == nil || IsNil(o.Values) {
		var ret []interface{}
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldValues) GetValuesOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *FieldValues) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []interface{} and assigns it to the Values field.
func (o *FieldValues) SetValues(v []interface{}) {
	o.Values = v
}

func (o FieldValues) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FieldValues) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_field"] = o.Field
	if !IsNil(o.Values) {
		toSerialize["_values"] = o.Values
	}
	return toSerialize, nil
}

func (o *FieldValues) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_field",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFieldValues := _FieldValues{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFieldValues)

	if err != nil {
		return err
	}

	*o = FieldValues(varFieldValues)

	return err
}

type NullableFieldValues struct {
	value *FieldValues
	isSet bool
}

func (v NullableFieldValues) Get() *FieldValues {
	return v.value
}

func (v *NullableFieldValues) Set(val *FieldValues) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldValues) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldValues(val *FieldValues) *NullableFieldValues {
	return &NullableFieldValues{value: val, isSet: true}
}

func (v NullableFieldValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


