/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ```

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OutputEmailIntakeApiProvider type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputEmailIntakeApiProvider{}

// OutputEmailIntakeApiProvider struct for OutputEmailIntakeApiProvider
type OutputEmailIntakeApiProvider struct {
	Name string `json:"name"`
}

type _OutputEmailIntakeApiProvider OutputEmailIntakeApiProvider

// NewOutputEmailIntakeApiProvider instantiates a new OutputEmailIntakeApiProvider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputEmailIntakeApiProvider(name string) *OutputEmailIntakeApiProvider {
	this := OutputEmailIntakeApiProvider{}
	this.Name = name
	return &this
}

// NewOutputEmailIntakeApiProviderWithDefaults instantiates a new OutputEmailIntakeApiProvider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputEmailIntakeApiProviderWithDefaults() *OutputEmailIntakeApiProvider {
	this := OutputEmailIntakeApiProvider{}
	return &this
}

// GetName returns the Name field value
func (o *OutputEmailIntakeApiProvider) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OutputEmailIntakeApiProvider) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OutputEmailIntakeApiProvider) SetName(v string) {
	o.Name = v
}

func (o OutputEmailIntakeApiProvider) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputEmailIntakeApiProvider) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *OutputEmailIntakeApiProvider) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputEmailIntakeApiProvider := _OutputEmailIntakeApiProvider{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputEmailIntakeApiProvider)

	if err != nil {
		return err
	}

	*o = OutputEmailIntakeApiProvider(varOutputEmailIntakeApiProvider)

	return err
}

type NullableOutputEmailIntakeApiProvider struct {
	value *OutputEmailIntakeApiProvider
	isSet bool
}

func (v NullableOutputEmailIntakeApiProvider) Get() *OutputEmailIntakeApiProvider {
	return v.value
}

func (v *NullableOutputEmailIntakeApiProvider) Set(val *OutputEmailIntakeApiProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputEmailIntakeApiProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputEmailIntakeApiProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputEmailIntakeApiProvider(val *OutputEmailIntakeApiProvider) *NullableOutputEmailIntakeApiProvider {
	return &NullableOutputEmailIntakeApiProvider{value: val, isSet: true}
}

func (v NullableOutputEmailIntakeApiProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputEmailIntakeApiProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
