/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ```

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OutputStreamAudit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputStreamAudit{}

// OutputStreamAudit struct for OutputStreamAudit
type OutputStreamAudit struct {
	Base    OutputAudit                 `json:"base"`
	Summary map[string]map[string]int32 `json:"summary"`
}

type _OutputStreamAudit OutputStreamAudit

// NewOutputStreamAudit instantiates a new OutputStreamAudit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputStreamAudit(base OutputAudit, summary map[string]map[string]int32) *OutputStreamAudit {
	this := OutputStreamAudit{}
	this.Base = base
	this.Summary = summary
	return &this
}

// NewOutputStreamAuditWithDefaults instantiates a new OutputStreamAudit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputStreamAuditWithDefaults() *OutputStreamAudit {
	this := OutputStreamAudit{}
	return &this
}

// GetBase returns the Base field value
func (o *OutputStreamAudit) GetBase() OutputAudit {
	if o == nil {
		var ret OutputAudit
		return ret
	}

	return o.Base
}

// GetBaseOk returns a tuple with the Base field value
// and a boolean to check if the value has been set.
func (o *OutputStreamAudit) GetBaseOk() (*OutputAudit, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Base, true
}

// SetBase sets field value
func (o *OutputStreamAudit) SetBase(v OutputAudit) {
	o.Base = v
}

// GetSummary returns the Summary field value
func (o *OutputStreamAudit) GetSummary() map[string]map[string]int32 {
	if o == nil {
		var ret map[string]map[string]int32
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *OutputStreamAudit) GetSummaryOk() (map[string]map[string]int32, bool) {
	if o == nil {
		return map[string]map[string]int32{}, false
	}
	return o.Summary, true
}

// SetSummary sets field value
func (o *OutputStreamAudit) SetSummary(v map[string]map[string]int32) {
	o.Summary = v
}

func (o OutputStreamAudit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputStreamAudit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["base"] = o.Base
	toSerialize["summary"] = o.Summary
	return toSerialize, nil
}

func (o *OutputStreamAudit) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"base",
		"summary",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputStreamAudit := _OutputStreamAudit{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputStreamAudit)

	if err != nil {
		return err
	}

	*o = OutputStreamAudit(varOutputStreamAudit)

	return err
}

type NullableOutputStreamAudit struct {
	value *OutputStreamAudit
	isSet bool
}

func (v NullableOutputStreamAudit) Get() *OutputStreamAudit {
	return v.value
}

func (v *NullableOutputStreamAudit) Set(val *OutputStreamAudit) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputStreamAudit) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputStreamAudit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputStreamAudit(val *OutputStreamAudit) *NullableOutputStreamAudit {
	return &NullableOutputStreamAudit{value: val, isSet: true}
}

func (v NullableOutputStreamAudit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputStreamAudit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
