/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Ko type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Ko{}

// Ko struct for Ko
type Ko struct {
	Errors map[string]string `json:"errors"`
}

type _Ko Ko

// NewKo instantiates a new Ko object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKo(errors map[string]string) *Ko {
	this := Ko{}
	this.Errors = errors
	return &this
}

// NewKoWithDefaults instantiates a new Ko object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKoWithDefaults() *Ko {
	this := Ko{}
	return &this
}

// GetErrors returns the Errors field value
func (o *Ko) GetErrors() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value
// and a boolean to check if the value has been set.
func (o *Ko) GetErrorsOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Errors, true
}

// SetErrors sets field value
func (o *Ko) SetErrors(v map[string]string) {
	o.Errors = v
}

func (o Ko) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Ko) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["errors"] = o.Errors
	return toSerialize, nil
}

func (o *Ko) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"errors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKo := _Ko{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKo)

	if err != nil {
		return err
	}

	*o = Ko(varKo)

	return err
}

type NullableKo struct {
	value *Ko
	isSet bool
}

func (v NullableKo) Get() *Ko {
	return v.value
}

func (v *NullableKo) Set(val *Ko) {
	v.value = val
	v.isSet = true
}

func (v NullableKo) IsSet() bool {
	return v.isSet
}

func (v *NullableKo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKo(val *Ko) *NullableKo {
	return &NullableKo{value: val, isSet: true}
}

func (v NullableKo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


