/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputListView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputListView{}

// OutputListView struct for OutputListView
type OutputListView struct {
	UnderscoreId string `json:"_id"`
	UnderscoreType string `json:"_type"`
	UnderscoreCreatedAt int64 `json:"_createdAt"`
	UnderscoreCreatedBy string `json:"_createdBy"`
	UnderscoreUpdatedAt *int64 `json:"_updatedAt,omitempty"`
	UnderscoreUpdatedBy *string `json:"_updatedBy,omitempty"`
	Name string `json:"name"`
	Entity string `json:"entity"`
	Filter map[string]interface{} `json:"filter"`
	ListOptions ListOptions `json:"listOptions"`
	SortList []string `json:"sortList,omitempty"`
	ShowColumns []string `json:"showColumns,omitempty"`
	IsShared bool `json:"isShared"`
}

type _OutputListView OutputListView

// NewOutputListView instantiates a new OutputListView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputListView(underscoreId string, underscoreType string, underscoreCreatedAt int64, underscoreCreatedBy string, name string, entity string, filter map[string]interface{}, listOptions ListOptions, isShared bool) *OutputListView {
	this := OutputListView{}
	this.UnderscoreId = underscoreId
	this.UnderscoreType = underscoreType
	this.UnderscoreCreatedAt = underscoreCreatedAt
	this.UnderscoreCreatedBy = underscoreCreatedBy
	this.Name = name
	this.Entity = entity
	this.Filter = filter
	this.ListOptions = listOptions
	this.IsShared = isShared
	return &this
}

// NewOutputListViewWithDefaults instantiates a new OutputListView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputListViewWithDefaults() *OutputListView {
	this := OutputListView{}
	return &this
}

// GetUnderscoreId returns the UnderscoreId field value
func (o *OutputListView) GetUnderscoreId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnderscoreId
}

// GetUnderscoreIdOk returns a tuple with the UnderscoreId field value
// and a boolean to check if the value has been set.
func (o *OutputListView) GetUnderscoreIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderscoreId, true
}

// SetUnderscoreId sets field value
func (o *OutputListView) SetUnderscoreId(v string) {
	o.UnderscoreId = v
}

// GetUnderscoreType returns the UnderscoreType field value
func (o *OutputListView) GetUnderscoreType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnderscoreType
}

// GetUnderscoreTypeOk returns a tuple with the UnderscoreType field value
// and a boolean to check if the value has been set.
func (o *OutputListView) GetUnderscoreTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderscoreType, true
}

// SetUnderscoreType sets field value
func (o *OutputListView) SetUnderscoreType(v string) {
	o.UnderscoreType = v
}

// GetUnderscoreCreatedAt returns the UnderscoreCreatedAt field value
func (o *OutputListView) GetUnderscoreCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UnderscoreCreatedAt
}

// GetUnderscoreCreatedAtOk returns a tuple with the UnderscoreCreatedAt field value
// and a boolean to check if the value has been set.
func (o *OutputListView) GetUnderscoreCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderscoreCreatedAt, true
}

// SetUnderscoreCreatedAt sets field value
func (o *OutputListView) SetUnderscoreCreatedAt(v int64) {
	o.UnderscoreCreatedAt = v
}

// GetUnderscoreCreatedBy returns the UnderscoreCreatedBy field value
func (o *OutputListView) GetUnderscoreCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnderscoreCreatedBy
}

// GetUnderscoreCreatedByOk returns a tuple with the UnderscoreCreatedBy field value
// and a boolean to check if the value has been set.
func (o *OutputListView) GetUnderscoreCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderscoreCreatedBy, true
}

// SetUnderscoreCreatedBy sets field value
func (o *OutputListView) SetUnderscoreCreatedBy(v string) {
	o.UnderscoreCreatedBy = v
}

// GetUnderscoreUpdatedAt returns the UnderscoreUpdatedAt field value if set, zero value otherwise.
func (o *OutputListView) GetUnderscoreUpdatedAt() int64 {
	if o == nil || IsNil(o.UnderscoreUpdatedAt) {
		var ret int64
		return ret
	}
	return *o.UnderscoreUpdatedAt
}

// GetUnderscoreUpdatedAtOk returns a tuple with the UnderscoreUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputListView) GetUnderscoreUpdatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.UnderscoreUpdatedAt) {
		return nil, false
	}
	return o.UnderscoreUpdatedAt, true
}

// HasUnderscoreUpdatedAt returns a boolean if a field has been set.
func (o *OutputListView) HasUnderscoreUpdatedAt() bool {
	if o != nil && !IsNil(o.UnderscoreUpdatedAt) {
		return true
	}

	return false
}

// SetUnderscoreUpdatedAt gets a reference to the given int64 and assigns it to the UnderscoreUpdatedAt field.
func (o *OutputListView) SetUnderscoreUpdatedAt(v int64) {
	o.UnderscoreUpdatedAt = &v
}

// GetUnderscoreUpdatedBy returns the UnderscoreUpdatedBy field value if set, zero value otherwise.
func (o *OutputListView) GetUnderscoreUpdatedBy() string {
	if o == nil || IsNil(o.UnderscoreUpdatedBy) {
		var ret string
		return ret
	}
	return *o.UnderscoreUpdatedBy
}

// GetUnderscoreUpdatedByOk returns a tuple with the UnderscoreUpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputListView) GetUnderscoreUpdatedByOk() (*string, bool) {
	if o == nil || IsNil(o.UnderscoreUpdatedBy) {
		return nil, false
	}
	return o.UnderscoreUpdatedBy, true
}

// HasUnderscoreUpdatedBy returns a boolean if a field has been set.
func (o *OutputListView) HasUnderscoreUpdatedBy() bool {
	if o != nil && !IsNil(o.UnderscoreUpdatedBy) {
		return true
	}

	return false
}

// SetUnderscoreUpdatedBy gets a reference to the given string and assigns it to the UnderscoreUpdatedBy field.
func (o *OutputListView) SetUnderscoreUpdatedBy(v string) {
	o.UnderscoreUpdatedBy = &v
}

// GetName returns the Name field value
func (o *OutputListView) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OutputListView) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OutputListView) SetName(v string) {
	o.Name = v
}

// GetEntity returns the Entity field value
func (o *OutputListView) GetEntity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Entity
}

// GetEntityOk returns a tuple with the Entity field value
// and a boolean to check if the value has been set.
func (o *OutputListView) GetEntityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entity, true
}

// SetEntity sets field value
func (o *OutputListView) SetEntity(v string) {
	o.Entity = v
}

// GetFilter returns the Filter field value
func (o *OutputListView) GetFilter() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Filter
}

// GetFilterOk returns a tuple with the Filter field value
// and a boolean to check if the value has been set.
func (o *OutputListView) GetFilterOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Filter, true
}

// SetFilter sets field value
func (o *OutputListView) SetFilter(v map[string]interface{}) {
	o.Filter = v
}

// GetListOptions returns the ListOptions field value
func (o *OutputListView) GetListOptions() ListOptions {
	if o == nil {
		var ret ListOptions
		return ret
	}

	return o.ListOptions
}

// GetListOptionsOk returns a tuple with the ListOptions field value
// and a boolean to check if the value has been set.
func (o *OutputListView) GetListOptionsOk() (*ListOptions, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ListOptions, true
}

// SetListOptions sets field value
func (o *OutputListView) SetListOptions(v ListOptions) {
	o.ListOptions = v
}

// GetSortList returns the SortList field value if set, zero value otherwise.
func (o *OutputListView) GetSortList() []string {
	if o == nil || IsNil(o.SortList) {
		var ret []string
		return ret
	}
	return o.SortList
}

// GetSortListOk returns a tuple with the SortList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputListView) GetSortListOk() ([]string, bool) {
	if o == nil || IsNil(o.SortList) {
		return nil, false
	}
	return o.SortList, true
}

// HasSortList returns a boolean if a field has been set.
func (o *OutputListView) HasSortList() bool {
	if o != nil && !IsNil(o.SortList) {
		return true
	}

	return false
}

// SetSortList gets a reference to the given []string and assigns it to the SortList field.
func (o *OutputListView) SetSortList(v []string) {
	o.SortList = v
}

// GetShowColumns returns the ShowColumns field value if set, zero value otherwise.
func (o *OutputListView) GetShowColumns() []string {
	if o == nil || IsNil(o.ShowColumns) {
		var ret []string
		return ret
	}
	return o.ShowColumns
}

// GetShowColumnsOk returns a tuple with the ShowColumns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputListView) GetShowColumnsOk() ([]string, bool) {
	if o == nil || IsNil(o.ShowColumns) {
		return nil, false
	}
	return o.ShowColumns, true
}

// HasShowColumns returns a boolean if a field has been set.
func (o *OutputListView) HasShowColumns() bool {
	if o != nil && !IsNil(o.ShowColumns) {
		return true
	}

	return false
}

// SetShowColumns gets a reference to the given []string and assigns it to the ShowColumns field.
func (o *OutputListView) SetShowColumns(v []string) {
	o.ShowColumns = v
}

// GetIsShared returns the IsShared field value
func (o *OutputListView) GetIsShared() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsShared
}

// GetIsSharedOk returns a tuple with the IsShared field value
// and a boolean to check if the value has been set.
func (o *OutputListView) GetIsSharedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsShared, true
}

// SetIsShared sets field value
func (o *OutputListView) SetIsShared(v bool) {
	o.IsShared = v
}

func (o OutputListView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputListView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_id"] = o.UnderscoreId
	toSerialize["_type"] = o.UnderscoreType
	toSerialize["_createdAt"] = o.UnderscoreCreatedAt
	toSerialize["_createdBy"] = o.UnderscoreCreatedBy
	if !IsNil(o.UnderscoreUpdatedAt) {
		toSerialize["_updatedAt"] = o.UnderscoreUpdatedAt
	}
	if !IsNil(o.UnderscoreUpdatedBy) {
		toSerialize["_updatedBy"] = o.UnderscoreUpdatedBy
	}
	toSerialize["name"] = o.Name
	toSerialize["entity"] = o.Entity
	toSerialize["filter"] = o.Filter
	toSerialize["listOptions"] = o.ListOptions
	if !IsNil(o.SortList) {
		toSerialize["sortList"] = o.SortList
	}
	if !IsNil(o.ShowColumns) {
		toSerialize["showColumns"] = o.ShowColumns
	}
	toSerialize["isShared"] = o.IsShared
	return toSerialize, nil
}

func (o *OutputListView) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_id",
		"_type",
		"_createdAt",
		"_createdBy",
		"name",
		"entity",
		"filter",
		"listOptions",
		"isShared",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputListView := _OutputListView{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputListView)

	if err != nil {
		return err
	}

	*o = OutputListView(varOutputListView)

	return err
}

type NullableOutputListView struct {
	value *OutputListView
	isSet bool
}

func (v NullableOutputListView) Get() *OutputListView {
	return v.value
}

func (v *NullableOutputListView) Set(val *OutputListView) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputListView) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputListView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputListView(val *OutputListView) *NullableOutputListView {
	return &NullableOutputListView{value: val, isSet: true}
}

func (v NullableOutputListView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputListView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


