/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Lte type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Lte{}

// Lte struct for Lte
type Lte struct {
	Lte FieldValue `json:"_lte"`
}

type _Lte Lte

// NewLte instantiates a new Lte object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLte(lte FieldValue) *Lte {
	this := Lte{}
	this.Lte = lte
	return &this
}

// NewLteWithDefaults instantiates a new Lte object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLteWithDefaults() *Lte {
	this := Lte{}
	return &this
}

// GetLte returns the Lte field value
func (o *Lte) GetLte() FieldValue {
	if o == nil {
		var ret FieldValue
		return ret
	}

	return o.Lte
}

// GetLteOk returns a tuple with the Lte field value
// and a boolean to check if the value has been set.
func (o *Lte) GetLteOk() (*FieldValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lte, true
}

// SetLte sets field value
func (o *Lte) SetLte(v FieldValue) {
	o.Lte = v
}

func (o Lte) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Lte) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_lte"] = o.Lte
	return toSerialize, nil
}

func (o *Lte) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_lte",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLte := _Lte{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLte)

	if err != nil {
		return err
	}

	*o = Lte(varLte)

	return err
}

type NullableLte struct {
	value *Lte
	isSet bool
}

func (v NullableLte) Get() *Lte {
	return v.value
}

func (v *NullableLte) Set(val *Lte) {
	v.value = val
	v.isSet = true
}

func (v NullableLte) IsSet() bool {
	return v.isSet
}

func (v *NullableLte) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLte(val *Lte) *NullableLte {
	return &NullableLte{value: val, isSet: true}
}

func (v NullableLte) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLte) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


