/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ```

API version: v1-5.5.11-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the OutputAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputAction{}

// OutputAction struct for OutputAction
type OutputAction struct {
	UnderscoreId        string     `json:"_id"`
	UnderscoreType      string     `json:"_type"`
	UnderscoreCreatedBy string     `json:"_createdBy"`
	UnderscoreUpdatedBy *string    `json:"_updatedBy,omitempty"`
	UnderscoreCreatedAt time.Time  `json:"_createdAt"`
	UnderscoreUpdatedAt *time.Time `json:"_updatedAt,omitempty"`
	ResponderId         string     `json:"responderId"`
	ResponderName       *string    `json:"responderName,omitempty"`
	ResponderDefinition *string    `json:"responderDefinition,omitempty"`
	CortexId            *string    `json:"cortexId,omitempty"`
	CortexJobId         *string    `json:"cortexJobId,omitempty"`
	ObjectType          string     `json:"objectType"`
	ObjectId            string     `json:"objectId"`
	Status              string     `json:"status"`
	StartDate           time.Time  `json:"startDate"`
	EndDate             *time.Time `json:"endDate,omitempty"`
	Operations          string     `json:"operations"`
	Report              string     `json:"report"`
}

type _OutputAction OutputAction

// NewOutputAction instantiates a new OutputAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputAction(underscoreId string, underscoreType string, underscoreCreatedBy string, underscoreCreatedAt time.Time, responderId string, objectType string, objectId string, status string, startDate time.Time, operations string, report string) *OutputAction {
	this := OutputAction{}
	this.UnderscoreId = underscoreId
	this.UnderscoreType = underscoreType
	this.UnderscoreCreatedBy = underscoreCreatedBy
	this.UnderscoreCreatedAt = underscoreCreatedAt
	this.ResponderId = responderId
	this.ObjectType = objectType
	this.ObjectId = objectId
	this.Status = status
	this.StartDate = startDate
	this.Operations = operations
	this.Report = report
	return &this
}

// NewOutputActionWithDefaults instantiates a new OutputAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputActionWithDefaults() *OutputAction {
	this := OutputAction{}
	return &this
}

// GetUnderscoreId returns the UnderscoreId field value
func (o *OutputAction) GetUnderscoreId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnderscoreId
}

// GetUnderscoreIdOk returns a tuple with the UnderscoreId field value
// and a boolean to check if the value has been set.
func (o *OutputAction) GetUnderscoreIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderscoreId, true
}

// SetUnderscoreId sets field value
func (o *OutputAction) SetUnderscoreId(v string) {
	o.UnderscoreId = v
}

// GetUnderscoreType returns the UnderscoreType field value
func (o *OutputAction) GetUnderscoreType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnderscoreType
}

// GetUnderscoreTypeOk returns a tuple with the UnderscoreType field value
// and a boolean to check if the value has been set.
func (o *OutputAction) GetUnderscoreTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderscoreType, true
}

// SetUnderscoreType sets field value
func (o *OutputAction) SetUnderscoreType(v string) {
	o.UnderscoreType = v
}

// GetUnderscoreCreatedBy returns the UnderscoreCreatedBy field value
func (o *OutputAction) GetUnderscoreCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnderscoreCreatedBy
}

// GetUnderscoreCreatedByOk returns a tuple with the UnderscoreCreatedBy field value
// and a boolean to check if the value has been set.
func (o *OutputAction) GetUnderscoreCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderscoreCreatedBy, true
}

// SetUnderscoreCreatedBy sets field value
func (o *OutputAction) SetUnderscoreCreatedBy(v string) {
	o.UnderscoreCreatedBy = v
}

// GetUnderscoreUpdatedBy returns the UnderscoreUpdatedBy field value if set, zero value otherwise.
func (o *OutputAction) GetUnderscoreUpdatedBy() string {
	if o == nil || IsNil(o.UnderscoreUpdatedBy) {
		var ret string
		return ret
	}
	return *o.UnderscoreUpdatedBy
}

// GetUnderscoreUpdatedByOk returns a tuple with the UnderscoreUpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputAction) GetUnderscoreUpdatedByOk() (*string, bool) {
	if o == nil || IsNil(o.UnderscoreUpdatedBy) {
		return nil, false
	}
	return o.UnderscoreUpdatedBy, true
}

// HasUnderscoreUpdatedBy returns a boolean if a field has been set.
func (o *OutputAction) HasUnderscoreUpdatedBy() bool {
	if o != nil && !IsNil(o.UnderscoreUpdatedBy) {
		return true
	}

	return false
}

// SetUnderscoreUpdatedBy gets a reference to the given string and assigns it to the UnderscoreUpdatedBy field.
func (o *OutputAction) SetUnderscoreUpdatedBy(v string) {
	o.UnderscoreUpdatedBy = &v
}

// GetUnderscoreCreatedAt returns the UnderscoreCreatedAt field value
func (o *OutputAction) GetUnderscoreCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UnderscoreCreatedAt
}

// GetUnderscoreCreatedAtOk returns a tuple with the UnderscoreCreatedAt field value
// and a boolean to check if the value has been set.
func (o *OutputAction) GetUnderscoreCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderscoreCreatedAt, true
}

// SetUnderscoreCreatedAt sets field value
func (o *OutputAction) SetUnderscoreCreatedAt(v time.Time) {
	o.UnderscoreCreatedAt = v
}

// GetUnderscoreUpdatedAt returns the UnderscoreUpdatedAt field value if set, zero value otherwise.
func (o *OutputAction) GetUnderscoreUpdatedAt() time.Time {
	if o == nil || IsNil(o.UnderscoreUpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UnderscoreUpdatedAt
}

// GetUnderscoreUpdatedAtOk returns a tuple with the UnderscoreUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputAction) GetUnderscoreUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UnderscoreUpdatedAt) {
		return nil, false
	}
	return o.UnderscoreUpdatedAt, true
}

// HasUnderscoreUpdatedAt returns a boolean if a field has been set.
func (o *OutputAction) HasUnderscoreUpdatedAt() bool {
	if o != nil && !IsNil(o.UnderscoreUpdatedAt) {
		return true
	}

	return false
}

// SetUnderscoreUpdatedAt gets a reference to the given time.Time and assigns it to the UnderscoreUpdatedAt field.
func (o *OutputAction) SetUnderscoreUpdatedAt(v time.Time) {
	o.UnderscoreUpdatedAt = &v
}

// GetResponderId returns the ResponderId field value
func (o *OutputAction) GetResponderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResponderId
}

// GetResponderIdOk returns a tuple with the ResponderId field value
// and a boolean to check if the value has been set.
func (o *OutputAction) GetResponderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResponderId, true
}

// SetResponderId sets field value
func (o *OutputAction) SetResponderId(v string) {
	o.ResponderId = v
}

// GetResponderName returns the ResponderName field value if set, zero value otherwise.
func (o *OutputAction) GetResponderName() string {
	if o == nil || IsNil(o.ResponderName) {
		var ret string
		return ret
	}
	return *o.ResponderName
}

// GetResponderNameOk returns a tuple with the ResponderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputAction) GetResponderNameOk() (*string, bool) {
	if o == nil || IsNil(o.ResponderName) {
		return nil, false
	}
	return o.ResponderName, true
}

// HasResponderName returns a boolean if a field has been set.
func (o *OutputAction) HasResponderName() bool {
	if o != nil && !IsNil(o.ResponderName) {
		return true
	}

	return false
}

// SetResponderName gets a reference to the given string and assigns it to the ResponderName field.
func (o *OutputAction) SetResponderName(v string) {
	o.ResponderName = &v
}

// GetResponderDefinition returns the ResponderDefinition field value if set, zero value otherwise.
func (o *OutputAction) GetResponderDefinition() string {
	if o == nil || IsNil(o.ResponderDefinition) {
		var ret string
		return ret
	}
	return *o.ResponderDefinition
}

// GetResponderDefinitionOk returns a tuple with the ResponderDefinition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputAction) GetResponderDefinitionOk() (*string, bool) {
	if o == nil || IsNil(o.ResponderDefinition) {
		return nil, false
	}
	return o.ResponderDefinition, true
}

// HasResponderDefinition returns a boolean if a field has been set.
func (o *OutputAction) HasResponderDefinition() bool {
	if o != nil && !IsNil(o.ResponderDefinition) {
		return true
	}

	return false
}

// SetResponderDefinition gets a reference to the given string and assigns it to the ResponderDefinition field.
func (o *OutputAction) SetResponderDefinition(v string) {
	o.ResponderDefinition = &v
}

// GetCortexId returns the CortexId field value if set, zero value otherwise.
func (o *OutputAction) GetCortexId() string {
	if o == nil || IsNil(o.CortexId) {
		var ret string
		return ret
	}
	return *o.CortexId
}

// GetCortexIdOk returns a tuple with the CortexId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputAction) GetCortexIdOk() (*string, bool) {
	if o == nil || IsNil(o.CortexId) {
		return nil, false
	}
	return o.CortexId, true
}

// HasCortexId returns a boolean if a field has been set.
func (o *OutputAction) HasCortexId() bool {
	if o != nil && !IsNil(o.CortexId) {
		return true
	}

	return false
}

// SetCortexId gets a reference to the given string and assigns it to the CortexId field.
func (o *OutputAction) SetCortexId(v string) {
	o.CortexId = &v
}

// GetCortexJobId returns the CortexJobId field value if set, zero value otherwise.
func (o *OutputAction) GetCortexJobId() string {
	if o == nil || IsNil(o.CortexJobId) {
		var ret string
		return ret
	}
	return *o.CortexJobId
}

// GetCortexJobIdOk returns a tuple with the CortexJobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputAction) GetCortexJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.CortexJobId) {
		return nil, false
	}
	return o.CortexJobId, true
}

// HasCortexJobId returns a boolean if a field has been set.
func (o *OutputAction) HasCortexJobId() bool {
	if o != nil && !IsNil(o.CortexJobId) {
		return true
	}

	return false
}

// SetCortexJobId gets a reference to the given string and assigns it to the CortexJobId field.
func (o *OutputAction) SetCortexJobId(v string) {
	o.CortexJobId = &v
}

// GetObjectType returns the ObjectType field value
func (o *OutputAction) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *OutputAction) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *OutputAction) SetObjectType(v string) {
	o.ObjectType = v
}

// GetObjectId returns the ObjectId field value
func (o *OutputAction) GetObjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectId
}

// GetObjectIdOk returns a tuple with the ObjectId field value
// and a boolean to check if the value has been set.
func (o *OutputAction) GetObjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectId, true
}

// SetObjectId sets field value
func (o *OutputAction) SetObjectId(v string) {
	o.ObjectId = v
}

// GetStatus returns the Status field value
func (o *OutputAction) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *OutputAction) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *OutputAction) SetStatus(v string) {
	o.Status = v
}

// GetStartDate returns the StartDate field value
func (o *OutputAction) GetStartDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value
// and a boolean to check if the value has been set.
func (o *OutputAction) GetStartDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartDate, true
}

// SetStartDate sets field value
func (o *OutputAction) SetStartDate(v time.Time) {
	o.StartDate = v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *OutputAction) GetEndDate() time.Time {
	if o == nil || IsNil(o.EndDate) {
		var ret time.Time
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputAction) GetEndDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *OutputAction) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given time.Time and assigns it to the EndDate field.
func (o *OutputAction) SetEndDate(v time.Time) {
	o.EndDate = &v
}

// GetOperations returns the Operations field value
func (o *OutputAction) GetOperations() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value
// and a boolean to check if the value has been set.
func (o *OutputAction) GetOperationsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operations, true
}

// SetOperations sets field value
func (o *OutputAction) SetOperations(v string) {
	o.Operations = v
}

// GetReport returns the Report field value
func (o *OutputAction) GetReport() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Report
}

// GetReportOk returns a tuple with the Report field value
// and a boolean to check if the value has been set.
func (o *OutputAction) GetReportOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Report, true
}

// SetReport sets field value
func (o *OutputAction) SetReport(v string) {
	o.Report = v
}

func (o OutputAction) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_id"] = o.UnderscoreId
	toSerialize["_type"] = o.UnderscoreType
	toSerialize["_createdBy"] = o.UnderscoreCreatedBy
	if !IsNil(o.UnderscoreUpdatedBy) {
		toSerialize["_updatedBy"] = o.UnderscoreUpdatedBy
	}
	toSerialize["_createdAt"] = o.UnderscoreCreatedAt
	if !IsNil(o.UnderscoreUpdatedAt) {
		toSerialize["_updatedAt"] = o.UnderscoreUpdatedAt
	}
	toSerialize["responderId"] = o.ResponderId
	if !IsNil(o.ResponderName) {
		toSerialize["responderName"] = o.ResponderName
	}
	if !IsNil(o.ResponderDefinition) {
		toSerialize["responderDefinition"] = o.ResponderDefinition
	}
	if !IsNil(o.CortexId) {
		toSerialize["cortexId"] = o.CortexId
	}
	if !IsNil(o.CortexJobId) {
		toSerialize["cortexJobId"] = o.CortexJobId
	}
	toSerialize["objectType"] = o.ObjectType
	toSerialize["objectId"] = o.ObjectId
	toSerialize["status"] = o.Status
	toSerialize["startDate"] = o.StartDate
	if !IsNil(o.EndDate) {
		toSerialize["endDate"] = o.EndDate
	}
	toSerialize["operations"] = o.Operations
	toSerialize["report"] = o.Report
	return toSerialize, nil
}

func (o *OutputAction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_id",
		"_type",
		"_createdBy",
		"_createdAt",
		"responderId",
		"objectType",
		"objectId",
		"status",
		"startDate",
		"operations",
		"report",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputAction := _OutputAction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputAction)

	if err != nil {
		return err
	}

	*o = OutputAction(varOutputAction)

	return err
}

type NullableOutputAction struct {
	value *OutputAction
	isSet bool
}

func (v NullableOutputAction) Get() *OutputAction {
	return v.value
}

func (v *NullableOutputAction) Set(val *OutputAction) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputAction) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputAction(val *OutputAction) *NullableOutputAction {
	return &NullableOutputAction{value: val, isSet: true}
}

func (v NullableOutputAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
