/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"fmt"
)

// InputLogLevel the model 'InputLogLevel'
type InputLogLevel string

// List of InputLogLevel
const (
	INPUTLOGLEVEL_ALL InputLogLevel = "ALL"
	INPUTLOGLEVEL_TRACE InputLogLevel = "TRACE"
	INPUTLOGLEVEL_DEBUG InputLogLevel = "DEBUG"
	INPUTLOGLEVEL_INFO InputLogLevel = "INFO"
	INPUTLOGLEVEL_WARN InputLogLevel = "WARN"
	INPUTLOGLEVEL_ERROR InputLogLevel = "ERROR"
	INPUTLOGLEVEL_OFF InputLogLevel = "OFF"
)

// All allowed values of InputLogLevel enum
var AllowedInputLogLevelEnumValues = []InputLogLevel{
	"ALL",
	"TRACE",
	"DEBUG",
	"INFO",
	"WARN",
	"ERROR",
	"OFF",
}

func (v *InputLogLevel) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := InputLogLevel(value)
	for _, existing := range AllowedInputLogLevelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid InputLogLevel", value)
}

// NewInputLogLevelFromValue returns a pointer to a valid InputLogLevel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewInputLogLevelFromValue(v string) (*InputLogLevel, error) {
	ev := InputLogLevel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for InputLogLevel: valid values are %v", v, AllowedInputLogLevelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v InputLogLevel) IsValid() bool {
	for _, existing := range AllowedInputLogLevelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to InputLogLevel value
func (v InputLogLevel) Ptr() *InputLogLevel {
	return &v
}

type NullableInputLogLevel struct {
	value *InputLogLevel
	isSet bool
}

func (v NullableInputLogLevel) Get() *InputLogLevel {
	return v.value
}

func (v *NullableInputLogLevel) Set(val *InputLogLevel) {
	v.value = val
	v.isSet = true
}

func (v NullableInputLogLevel) IsSet() bool {
	return v.isSet
}

func (v *NullableInputLogLevel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputLogLevel(val *InputLogLevel) *NullableInputLogLevel {
	return &NullableInputLogLevel{value: val, isSet: true}
}

func (v NullableInputLogLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputLogLevel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

