/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ```

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InputQueryGenericOperation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputQueryGenericOperation{}

// InputQueryGenericOperation struct for InputQueryGenericOperation
type InputQueryGenericOperation struct {
	Name string `json:"_name"`
}

type _InputQueryGenericOperation InputQueryGenericOperation

// NewInputQueryGenericOperation instantiates a new InputQueryGenericOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputQueryGenericOperation(name string) *InputQueryGenericOperation {
	this := InputQueryGenericOperation{}
	this.Name = name
	return &this
}

// NewInputQueryGenericOperationWithDefaults instantiates a new InputQueryGenericOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputQueryGenericOperationWithDefaults() *InputQueryGenericOperation {
	this := InputQueryGenericOperation{}
	return &this
}

// GetName returns the Name field value
func (o *InputQueryGenericOperation) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InputQueryGenericOperation) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InputQueryGenericOperation) SetName(v string) {
	o.Name = v
}

func (o InputQueryGenericOperation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputQueryGenericOperation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_name"] = o.Name
	return toSerialize, nil
}

func (o *InputQueryGenericOperation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputQueryGenericOperation := _InputQueryGenericOperation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputQueryGenericOperation)

	if err != nil {
		return err
	}

	*o = InputQueryGenericOperation(varInputQueryGenericOperation)

	return err
}

type NullableInputQueryGenericOperation struct {
	value *InputQueryGenericOperation
	isSet bool
}

func (v NullableInputQueryGenericOperation) Get() *InputQueryGenericOperation {
	return v.value
}

func (v *NullableInputQueryGenericOperation) Set(val *InputQueryGenericOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableInputQueryGenericOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableInputQueryGenericOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputQueryGenericOperation(val *InputQueryGenericOperation) *NullableInputQueryGenericOperation {
	return &NullableInputQueryGenericOperation{value: val, isSet: true}
}

func (v NullableInputQueryGenericOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputQueryGenericOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
