/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputTimelineEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputTimelineEvent{}

// OutputTimelineEvent struct for OutputTimelineEvent
type OutputTimelineEvent struct {
	Date int32 `json:"date"`
	Kind string `json:"kind"`
	Entity string `json:"entity"`
	EntityId string `json:"entityId"`
	Details map[string]interface{} `json:"details"`
	EndDate *int32 `json:"endDate,omitempty"`
}

type _OutputTimelineEvent OutputTimelineEvent

// NewOutputTimelineEvent instantiates a new OutputTimelineEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputTimelineEvent(date int32, kind string, entity string, entityId string, details map[string]interface{}) *OutputTimelineEvent {
	this := OutputTimelineEvent{}
	this.Date = date
	this.Kind = kind
	this.Entity = entity
	this.EntityId = entityId
	this.Details = details
	return &this
}

// NewOutputTimelineEventWithDefaults instantiates a new OutputTimelineEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputTimelineEventWithDefaults() *OutputTimelineEvent {
	this := OutputTimelineEvent{}
	return &this
}

// GetDate returns the Date field value
func (o *OutputTimelineEvent) GetDate() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *OutputTimelineEvent) GetDateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *OutputTimelineEvent) SetDate(v int32) {
	o.Date = v
}

// GetKind returns the Kind field value
func (o *OutputTimelineEvent) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *OutputTimelineEvent) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *OutputTimelineEvent) SetKind(v string) {
	o.Kind = v
}

// GetEntity returns the Entity field value
func (o *OutputTimelineEvent) GetEntity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Entity
}

// GetEntityOk returns a tuple with the Entity field value
// and a boolean to check if the value has been set.
func (o *OutputTimelineEvent) GetEntityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entity, true
}

// SetEntity sets field value
func (o *OutputTimelineEvent) SetEntity(v string) {
	o.Entity = v
}

// GetEntityId returns the EntityId field value
func (o *OutputTimelineEvent) GetEntityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntityId
}

// GetEntityIdOk returns a tuple with the EntityId field value
// and a boolean to check if the value has been set.
func (o *OutputTimelineEvent) GetEntityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityId, true
}

// SetEntityId sets field value
func (o *OutputTimelineEvent) SetEntityId(v string) {
	o.EntityId = v
}

// GetDetails returns the Details field value
func (o *OutputTimelineEvent) GetDetails() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *OutputTimelineEvent) GetDetailsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Details, true
}

// SetDetails sets field value
func (o *OutputTimelineEvent) SetDetails(v map[string]interface{}) {
	o.Details = v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *OutputTimelineEvent) GetEndDate() int32 {
	if o == nil || IsNil(o.EndDate) {
		var ret int32
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputTimelineEvent) GetEndDateOk() (*int32, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *OutputTimelineEvent) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given int32 and assigns it to the EndDate field.
func (o *OutputTimelineEvent) SetEndDate(v int32) {
	o.EndDate = &v
}

func (o OutputTimelineEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputTimelineEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["kind"] = o.Kind
	toSerialize["entity"] = o.Entity
	toSerialize["entityId"] = o.EntityId
	toSerialize["details"] = o.Details
	if !IsNil(o.EndDate) {
		toSerialize["endDate"] = o.EndDate
	}
	return toSerialize, nil
}

func (o *OutputTimelineEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"kind",
		"entity",
		"entityId",
		"details",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputTimelineEvent := _OutputTimelineEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputTimelineEvent)

	if err != nil {
		return err
	}

	*o = OutputTimelineEvent(varOutputTimelineEvent)

	return err
}

type NullableOutputTimelineEvent struct {
	value *OutputTimelineEvent
	isSet bool
}

func (v NullableOutputTimelineEvent) Get() *OutputTimelineEvent {
	return v.value
}

func (v *NullableOutputTimelineEvent) Set(val *OutputTimelineEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputTimelineEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputTimelineEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputTimelineEvent(val *OutputTimelineEvent) *NullableOutputTimelineEvent {
	return &NullableOutputTimelineEvent{value: val, isSet: true}
}

func (v NullableOutputTimelineEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputTimelineEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


