/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ```

API version: v1-5.5.11-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OrganisationAccess type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganisationAccess{}

// OrganisationAccess struct for OrganisationAccess
type OrganisationAccess struct {
	Kind string `json:"_kind"`
}

type _OrganisationAccess OrganisationAccess

// NewOrganisationAccess instantiates a new OrganisationAccess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganisationAccess(kind string) *OrganisationAccess {
	this := OrganisationAccess{}
	this.Kind = kind
	return &this
}

// NewOrganisationAccessWithDefaults instantiates a new OrganisationAccess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganisationAccessWithDefaults() *OrganisationAccess {
	this := OrganisationAccess{}
	return &this
}

// GetKind returns the Kind field value
func (o *OrganisationAccess) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *OrganisationAccess) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *OrganisationAccess) SetKind(v string) {
	o.Kind = v
}

func (o OrganisationAccess) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganisationAccess) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_kind"] = o.Kind
	return toSerialize, nil
}

func (o *OrganisationAccess) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganisationAccess := _OrganisationAccess{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganisationAccess)

	if err != nil {
		return err
	}

	*o = OrganisationAccess(varOrganisationAccess)

	return err
}

type NullableOrganisationAccess struct {
	value *OrganisationAccess
	isSet bool
}

func (v NullableOrganisationAccess) Get() *OrganisationAccess {
	return v.value
}

func (v *NullableOrganisationAccess) Set(val *OrganisationAccess) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganisationAccess) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganisationAccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganisationAccess(val *OrganisationAccess) *NullableOrganisationAccess {
	return &NullableOrganisationAccess{value: val, isSet: true}
}

func (v NullableOrganisationAccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganisationAccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
