/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"fmt"
)

// EmailIntakeProviderName the model 'EmailIntakeProviderName'
type EmailIntakeProviderName string

// List of EmailIntakeProviderName
const (
	EMAILINTAKEPROVIDERNAME_IMAP EmailIntakeProviderName = "imap"
	EMAILINTAKEPROVIDERNAME_OFFICE365 EmailIntakeProviderName = "office365"
	EMAILINTAKEPROVIDERNAME_GOOGLE_WORKSPACE EmailIntakeProviderName = "google-workspace"
	EMAILINTAKEPROVIDERNAME_MS_GRAPH365 EmailIntakeProviderName = "MSGraph365"
)

// All allowed values of EmailIntakeProviderName enum
var AllowedEmailIntakeProviderNameEnumValues = []EmailIntakeProviderName{
	"imap",
	"office365",
	"google-workspace",
	"MSGraph365",
}

func (v *EmailIntakeProviderName) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EmailIntakeProviderName(value)
	for _, existing := range AllowedEmailIntakeProviderNameEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EmailIntakeProviderName", value)
}

// NewEmailIntakeProviderNameFromValue returns a pointer to a valid EmailIntakeProviderName
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEmailIntakeProviderNameFromValue(v string) (*EmailIntakeProviderName, error) {
	ev := EmailIntakeProviderName(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EmailIntakeProviderName: valid values are %v", v, AllowedEmailIntakeProviderNameEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EmailIntakeProviderName) IsValid() bool {
	for _, existing := range AllowedEmailIntakeProviderNameEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EmailIntakeProviderName value
func (v EmailIntakeProviderName) Ptr() *EmailIntakeProviderName {
	return &v
}

type NullableEmailIntakeProviderName struct {
	value *EmailIntakeProviderName
	isSet bool
}

func (v NullableEmailIntakeProviderName) Get() *EmailIntakeProviderName {
	return v.value
}

func (v *NullableEmailIntakeProviderName) Set(val *EmailIntakeProviderName) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailIntakeProviderName) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailIntakeProviderName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailIntakeProviderName(val *EmailIntakeProviderName) *NullableEmailIntakeProviderName {
	return &NullableEmailIntakeProviderName{value: val, isSet: true}
}

func (v NullableEmailIntakeProviderName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailIntakeProviderName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

