/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// Access - struct for Access
type Access struct {
	AllExternalAccess *AllExternalAccess
	ExternalAccess *ExternalAccess
	OrganisationAccess *OrganisationAccess
	UserAccess *UserAccess
}

// AllExternalAccessAsAccess is a convenience function that returns AllExternalAccess wrapped in Access
func AllExternalAccessAsAccess(v *AllExternalAccess) Access {
	return Access{
		AllExternalAccess: v,
	}
}

// ExternalAccessAsAccess is a convenience function that returns ExternalAccess wrapped in Access
func ExternalAccessAsAccess(v *ExternalAccess) Access {
	return Access{
		ExternalAccess: v,
	}
}

// OrganisationAccessAsAccess is a convenience function that returns OrganisationAccess wrapped in Access
func OrganisationAccessAsAccess(v *OrganisationAccess) Access {
	return Access{
		OrganisationAccess: v,
	}
}

// UserAccessAsAccess is a convenience function that returns UserAccess wrapped in Access
func UserAccessAsAccess(v *UserAccess) Access {
	return Access{
		UserAccess: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Access) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AllExternalAccess
	err = newStrictDecoder(data).Decode(&dst.AllExternalAccess)
	if err == nil {
		jsonAllExternalAccess, _ := json.Marshal(dst.AllExternalAccess)
		if string(jsonAllExternalAccess) == "{}" { // empty struct
			dst.AllExternalAccess = nil
		} else {
			if err = validator.Validate(dst.AllExternalAccess); err != nil {
				dst.AllExternalAccess = nil
			} else {
				match++
			}
		}
	} else {
		dst.AllExternalAccess = nil
	}

	// try to unmarshal data into ExternalAccess
	err = newStrictDecoder(data).Decode(&dst.ExternalAccess)
	if err == nil {
		jsonExternalAccess, _ := json.Marshal(dst.ExternalAccess)
		if string(jsonExternalAccess) == "{}" { // empty struct
			dst.ExternalAccess = nil
		} else {
			if err = validator.Validate(dst.ExternalAccess); err != nil {
				dst.ExternalAccess = nil
			} else {
				match++
			}
		}
	} else {
		dst.ExternalAccess = nil
	}

	// try to unmarshal data into OrganisationAccess
	err = newStrictDecoder(data).Decode(&dst.OrganisationAccess)
	if err == nil {
		jsonOrganisationAccess, _ := json.Marshal(dst.OrganisationAccess)
		if string(jsonOrganisationAccess) == "{}" { // empty struct
			dst.OrganisationAccess = nil
		} else {
			if err = validator.Validate(dst.OrganisationAccess); err != nil {
				dst.OrganisationAccess = nil
			} else {
				match++
			}
		}
	} else {
		dst.OrganisationAccess = nil
	}

	// try to unmarshal data into UserAccess
	err = newStrictDecoder(data).Decode(&dst.UserAccess)
	if err == nil {
		jsonUserAccess, _ := json.Marshal(dst.UserAccess)
		if string(jsonUserAccess) == "{}" { // empty struct
			dst.UserAccess = nil
		} else {
			if err = validator.Validate(dst.UserAccess); err != nil {
				dst.UserAccess = nil
			} else {
				match++
			}
		}
	} else {
		dst.UserAccess = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AllExternalAccess = nil
		dst.ExternalAccess = nil
		dst.OrganisationAccess = nil
		dst.UserAccess = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Access)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Access)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Access) MarshalJSON() ([]byte, error) {
	if src.AllExternalAccess != nil {
		return json.Marshal(&src.AllExternalAccess)
	}

	if src.ExternalAccess != nil {
		return json.Marshal(&src.ExternalAccess)
	}

	if src.OrganisationAccess != nil {
		return json.Marshal(&src.OrganisationAccess)
	}

	if src.UserAccess != nil {
		return json.Marshal(&src.UserAccess)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Access) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AllExternalAccess != nil {
		return obj.AllExternalAccess
	}

	if obj.ExternalAccess != nil {
		return obj.ExternalAccess
	}

	if obj.OrganisationAccess != nil {
		return obj.OrganisationAccess
	}

	if obj.UserAccess != nil {
		return obj.UserAccess
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Access) GetActualInstanceValue() (interface{}) {
	if obj.AllExternalAccess != nil {
		return *obj.AllExternalAccess
	}

	if obj.ExternalAccess != nil {
		return *obj.ExternalAccess
	}

	if obj.OrganisationAccess != nil {
		return *obj.OrganisationAccess
	}

	if obj.UserAccess != nil {
		return *obj.UserAccess
	}

	// all schemas are nil
	return nil
}

type NullableAccess struct {
	value *Access
	isSet bool
}

func (v NullableAccess) Get() *Access {
	return v.value
}

func (v *NullableAccess) Set(val *Access) {
	v.value = val
	v.isSet = true
}

func (v NullableAccess) IsSet() bool {
	return v.isSet
}

func (v *NullableAccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccess(val *Access) *NullableAccess {
	return &NullableAccess{value: val, isSet: true}
}

func (v NullableAccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


