/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"os"
	"bytes"
	"fmt"
)

// checks if the InputCreateLog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputCreateLog{}

// InputCreateLog struct for InputCreateLog
type InputCreateLog struct {
	Message string `json:"message"`
	StartDate *int64 `json:"startDate,omitempty"`
	IncludeInTimeline *int64 `json:"includeInTimeline,omitempty"`
	// ignored with json content, use a multipart if you want to pass attachments
	Attachments []*os.File `json:"attachments,omitempty"`
}

type _InputCreateLog InputCreateLog

// NewInputCreateLog instantiates a new InputCreateLog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputCreateLog(message string) *InputCreateLog {
	this := InputCreateLog{}
	this.Message = message
	return &this
}

// NewInputCreateLogWithDefaults instantiates a new InputCreateLog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputCreateLogWithDefaults() *InputCreateLog {
	this := InputCreateLog{}
	return &this
}

// GetMessage returns the Message field value
func (o *InputCreateLog) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *InputCreateLog) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *InputCreateLog) SetMessage(v string) {
	o.Message = v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *InputCreateLog) GetStartDate() int64 {
	if o == nil || IsNil(o.StartDate) {
		var ret int64
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputCreateLog) GetStartDateOk() (*int64, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *InputCreateLog) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given int64 and assigns it to the StartDate field.
func (o *InputCreateLog) SetStartDate(v int64) {
	o.StartDate = &v
}

// GetIncludeInTimeline returns the IncludeInTimeline field value if set, zero value otherwise.
func (o *InputCreateLog) GetIncludeInTimeline() int64 {
	if o == nil || IsNil(o.IncludeInTimeline) {
		var ret int64
		return ret
	}
	return *o.IncludeInTimeline
}

// GetIncludeInTimelineOk returns a tuple with the IncludeInTimeline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputCreateLog) GetIncludeInTimelineOk() (*int64, bool) {
	if o == nil || IsNil(o.IncludeInTimeline) {
		return nil, false
	}
	return o.IncludeInTimeline, true
}

// HasIncludeInTimeline returns a boolean if a field has been set.
func (o *InputCreateLog) HasIncludeInTimeline() bool {
	if o != nil && !IsNil(o.IncludeInTimeline) {
		return true
	}

	return false
}

// SetIncludeInTimeline gets a reference to the given int64 and assigns it to the IncludeInTimeline field.
func (o *InputCreateLog) SetIncludeInTimeline(v int64) {
	o.IncludeInTimeline = &v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *InputCreateLog) GetAttachments() []*os.File {
	if o == nil || IsNil(o.Attachments) {
		var ret []*os.File
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputCreateLog) GetAttachmentsOk() ([]*os.File, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *InputCreateLog) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []*os.File and assigns it to the Attachments field.
func (o *InputCreateLog) SetAttachments(v []*os.File) {
	o.Attachments = v
}

func (o InputCreateLog) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputCreateLog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	if !IsNil(o.IncludeInTimeline) {
		toSerialize["includeInTimeline"] = o.IncludeInTimeline
	}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	return toSerialize, nil
}

func (o *InputCreateLog) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputCreateLog := _InputCreateLog{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputCreateLog)

	if err != nil {
		return err
	}

	*o = InputCreateLog(varInputCreateLog)

	return err
}

type NullableInputCreateLog struct {
	value *InputCreateLog
	isSet bool
}

func (v NullableInputCreateLog) Get() *InputCreateLog {
	return v.value
}

func (v *NullableInputCreateLog) Set(val *InputCreateLog) {
	v.value = val
	v.isSet = true
}

func (v NullableInputCreateLog) IsSet() bool {
	return v.isSet
}

func (v *NullableInputCreateLog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputCreateLog(val *InputCreateLog) *NullableInputCreateLog {
	return &NullableInputCreateLog{value: val, isSet: true}
}

func (v NullableInputCreateLog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputCreateLog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


