/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"fmt"
)

// CustomFieldType the model 'CustomFieldType'
type CustomFieldType string

// List of CustomFieldType
const (
	CUSTOMFIELDTYPE_STRING CustomFieldType = "string"
	CUSTOMFIELDTYPE_INTEGER CustomFieldType = "integer"
	CUSTOMFIELDTYPE_FLOAT CustomFieldType = "float"
	CUSTOMFIELDTYPE_BOOLEAN CustomFieldType = "boolean"
	CUSTOMFIELDTYPE_DATE CustomFieldType = "date"
	CUSTOMFIELDTYPE_URL CustomFieldType = "url"
)

// All allowed values of CustomFieldType enum
var AllowedCustomFieldTypeEnumValues = []CustomFieldType{
	"string",
	"integer",
	"float",
	"boolean",
	"date",
	"url",
}

func (v *CustomFieldType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CustomFieldType(value)
	for _, existing := range AllowedCustomFieldTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CustomFieldType", value)
}

// NewCustomFieldTypeFromValue returns a pointer to a valid CustomFieldType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCustomFieldTypeFromValue(v string) (*CustomFieldType, error) {
	ev := CustomFieldType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CustomFieldType: valid values are %v", v, AllowedCustomFieldTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CustomFieldType) IsValid() bool {
	for _, existing := range AllowedCustomFieldTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CustomFieldType value
func (v CustomFieldType) Ptr() *CustomFieldType {
	return &v
}

type NullableCustomFieldType struct {
	value *CustomFieldType
	isSet bool
}

func (v NullableCustomFieldType) Get() *CustomFieldType {
	return v.value
}

func (v *NullableCustomFieldType) Set(val *CustomFieldType) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomFieldType) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomFieldType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomFieldType(val *CustomFieldType) *NullableCustomFieldType {
	return &NullableCustomFieldType{value: val, isSet: true}
}

func (v NullableCustomFieldType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomFieldType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

