/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputEmailIntakeBasicAuth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputEmailIntakeBasicAuth{}

// OutputEmailIntakeBasicAuth struct for OutputEmailIntakeBasicAuth
type OutputEmailIntakeBasicAuth struct {
	Password string `json:"password"`
}

type _OutputEmailIntakeBasicAuth OutputEmailIntakeBasicAuth

// NewOutputEmailIntakeBasicAuth instantiates a new OutputEmailIntakeBasicAuth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputEmailIntakeBasicAuth(password string) *OutputEmailIntakeBasicAuth {
	this := OutputEmailIntakeBasicAuth{}
	this.Password = password
	return &this
}

// NewOutputEmailIntakeBasicAuthWithDefaults instantiates a new OutputEmailIntakeBasicAuth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputEmailIntakeBasicAuthWithDefaults() *OutputEmailIntakeBasicAuth {
	this := OutputEmailIntakeBasicAuth{}
	return &this
}

// GetPassword returns the Password field value
func (o *OutputEmailIntakeBasicAuth) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *OutputEmailIntakeBasicAuth) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *OutputEmailIntakeBasicAuth) SetPassword(v string) {
	o.Password = v
}

func (o OutputEmailIntakeBasicAuth) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputEmailIntakeBasicAuth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *OutputEmailIntakeBasicAuth) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputEmailIntakeBasicAuth := _OutputEmailIntakeBasicAuth{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputEmailIntakeBasicAuth)

	if err != nil {
		return err
	}

	*o = OutputEmailIntakeBasicAuth(varOutputEmailIntakeBasicAuth)

	return err
}

type NullableOutputEmailIntakeBasicAuth struct {
	value *OutputEmailIntakeBasicAuth
	isSet bool
}

func (v NullableOutputEmailIntakeBasicAuth) Get() *OutputEmailIntakeBasicAuth {
	return v.value
}

func (v *NullableOutputEmailIntakeBasicAuth) Set(val *OutputEmailIntakeBasicAuth) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputEmailIntakeBasicAuth) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputEmailIntakeBasicAuth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputEmailIntakeBasicAuth(val *OutputEmailIntakeBasicAuth) *NullableOutputEmailIntakeBasicAuth {
	return &NullableOutputEmailIntakeBasicAuth{value: val, isSet: true}
}

func (v NullableOutputEmailIntakeBasicAuth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputEmailIntakeBasicAuth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


