/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Imports type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Imports{}

// Imports struct for Imports
type Imports struct {
	MitreCatalog string `json:"mitreCatalog"`
}

type _Imports Imports

// NewImports instantiates a new Imports object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImports(mitreCatalog string) *Imports {
	this := Imports{}
	this.MitreCatalog = mitreCatalog
	return &this
}

// NewImportsWithDefaults instantiates a new Imports object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportsWithDefaults() *Imports {
	this := Imports{}
	return &this
}

// GetMitreCatalog returns the MitreCatalog field value
func (o *Imports) GetMitreCatalog() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MitreCatalog
}

// GetMitreCatalogOk returns a tuple with the MitreCatalog field value
// and a boolean to check if the value has been set.
func (o *Imports) GetMitreCatalogOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MitreCatalog, true
}

// SetMitreCatalog sets field value
func (o *Imports) SetMitreCatalog(v string) {
	o.MitreCatalog = v
}

func (o Imports) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Imports) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mitreCatalog"] = o.MitreCatalog
	return toSerialize, nil
}

func (o *Imports) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mitreCatalog",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImports := _Imports{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImports)

	if err != nil {
		return err
	}

	*o = Imports(varImports)

	return err
}

type NullableImports struct {
	value *Imports
	isSet bool
}

func (v NullableImports) Get() *Imports {
	return v.value
}

func (v *NullableImports) Set(val *Imports) {
	v.value = val
	v.isSet = true
}

func (v NullableImports) IsSet() bool {
	return v.isSet
}

func (v *NullableImports) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImports(val *Imports) *NullableImports {
	return &NullableImports{value: val, isSet: true}
}

func (v NullableImports) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImports) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


