/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InputManageCaseAccess type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputManageCaseAccess{}

// InputManageCaseAccess struct for InputManageCaseAccess
type InputManageCaseAccess struct {
	Access Access `json:"access"`
}

type _InputManageCaseAccess InputManageCaseAccess

// NewInputManageCaseAccess instantiates a new InputManageCaseAccess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputManageCaseAccess(access Access) *InputManageCaseAccess {
	this := InputManageCaseAccess{}
	this.Access = access
	return &this
}

// NewInputManageCaseAccessWithDefaults instantiates a new InputManageCaseAccess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputManageCaseAccessWithDefaults() *InputManageCaseAccess {
	this := InputManageCaseAccess{}
	return &this
}

// GetAccess returns the Access field value
func (o *InputManageCaseAccess) GetAccess() Access {
	if o == nil {
		var ret Access
		return ret
	}

	return o.Access
}

// GetAccessOk returns a tuple with the Access field value
// and a boolean to check if the value has been set.
func (o *InputManageCaseAccess) GetAccessOk() (*Access, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Access, true
}

// SetAccess sets field value
func (o *InputManageCaseAccess) SetAccess(v Access) {
	o.Access = v
}

func (o InputManageCaseAccess) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputManageCaseAccess) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access"] = o.Access
	return toSerialize, nil
}

func (o *InputManageCaseAccess) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputManageCaseAccess := _InputManageCaseAccess{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputManageCaseAccess)

	if err != nil {
		return err
	}

	*o = InputManageCaseAccess(varInputManageCaseAccess)

	return err
}

type NullableInputManageCaseAccess struct {
	value *InputManageCaseAccess
	isSet bool
}

func (v NullableInputManageCaseAccess) Get() *InputManageCaseAccess {
	return v.value
}

func (v *NullableInputManageCaseAccess) Set(val *InputManageCaseAccess) {
	v.value = val
	v.isSet = true
}

func (v NullableInputManageCaseAccess) IsSet() bool {
	return v.isSet
}

func (v *NullableInputManageCaseAccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputManageCaseAccess(val *InputManageCaseAccess) *NullableInputManageCaseAccess {
	return &NullableInputManageCaseAccess{value: val, isSet: true}
}

func (v NullableInputManageCaseAccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputManageCaseAccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


