/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ```

API version: v1-5.5.11-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OutputCatalogOfPattern type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputCatalogOfPattern{}

// OutputCatalogOfPattern struct for OutputCatalogOfPattern
type OutputCatalogOfPattern struct {
	UnderscoreId   string                 `json:"_id"`
	UnderscoreType string                 `json:"_type"`
	CreatedBy      string                 `json:"createdBy"`
	CreatedAt      int64                  `json:"createdAt"`
	UpdatedAt      *int64                 `json:"updatedAt,omitempty"`
	Name           string                 `json:"name"`
	Description    *string                `json:"description,omitempty"`
	Variant        *string                `json:"variant,omitempty"`
	ExtraData      map[string]interface{} `json:"extraData"`
}

type _OutputCatalogOfPattern OutputCatalogOfPattern

// NewOutputCatalogOfPattern instantiates a new OutputCatalogOfPattern object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputCatalogOfPattern(underscoreId string, underscoreType string, createdBy string, createdAt int64, name string, extraData map[string]interface{}) *OutputCatalogOfPattern {
	this := OutputCatalogOfPattern{}
	this.UnderscoreId = underscoreId
	this.UnderscoreType = underscoreType
	this.CreatedBy = createdBy
	this.CreatedAt = createdAt
	this.Name = name
	this.ExtraData = extraData
	return &this
}

// NewOutputCatalogOfPatternWithDefaults instantiates a new OutputCatalogOfPattern object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputCatalogOfPatternWithDefaults() *OutputCatalogOfPattern {
	this := OutputCatalogOfPattern{}
	return &this
}

// GetUnderscoreId returns the UnderscoreId field value
func (o *OutputCatalogOfPattern) GetUnderscoreId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnderscoreId
}

// GetUnderscoreIdOk returns a tuple with the UnderscoreId field value
// and a boolean to check if the value has been set.
func (o *OutputCatalogOfPattern) GetUnderscoreIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderscoreId, true
}

// SetUnderscoreId sets field value
func (o *OutputCatalogOfPattern) SetUnderscoreId(v string) {
	o.UnderscoreId = v
}

// GetUnderscoreType returns the UnderscoreType field value
func (o *OutputCatalogOfPattern) GetUnderscoreType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnderscoreType
}

// GetUnderscoreTypeOk returns a tuple with the UnderscoreType field value
// and a boolean to check if the value has been set.
func (o *OutputCatalogOfPattern) GetUnderscoreTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderscoreType, true
}

// SetUnderscoreType sets field value
func (o *OutputCatalogOfPattern) SetUnderscoreType(v string) {
	o.UnderscoreType = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *OutputCatalogOfPattern) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *OutputCatalogOfPattern) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *OutputCatalogOfPattern) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *OutputCatalogOfPattern) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *OutputCatalogOfPattern) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *OutputCatalogOfPattern) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *OutputCatalogOfPattern) GetUpdatedAt() int64 {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret int64
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputCatalogOfPattern) GetUpdatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *OutputCatalogOfPattern) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int64 and assigns it to the UpdatedAt field.
func (o *OutputCatalogOfPattern) SetUpdatedAt(v int64) {
	o.UpdatedAt = &v
}

// GetName returns the Name field value
func (o *OutputCatalogOfPattern) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OutputCatalogOfPattern) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OutputCatalogOfPattern) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *OutputCatalogOfPattern) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputCatalogOfPattern) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *OutputCatalogOfPattern) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *OutputCatalogOfPattern) SetDescription(v string) {
	o.Description = &v
}

// GetVariant returns the Variant field value if set, zero value otherwise.
func (o *OutputCatalogOfPattern) GetVariant() string {
	if o == nil || IsNil(o.Variant) {
		var ret string
		return ret
	}
	return *o.Variant
}

// GetVariantOk returns a tuple with the Variant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputCatalogOfPattern) GetVariantOk() (*string, bool) {
	if o == nil || IsNil(o.Variant) {
		return nil, false
	}
	return o.Variant, true
}

// HasVariant returns a boolean if a field has been set.
func (o *OutputCatalogOfPattern) HasVariant() bool {
	if o != nil && !IsNil(o.Variant) {
		return true
	}

	return false
}

// SetVariant gets a reference to the given string and assigns it to the Variant field.
func (o *OutputCatalogOfPattern) SetVariant(v string) {
	o.Variant = &v
}

// GetExtraData returns the ExtraData field value
func (o *OutputCatalogOfPattern) GetExtraData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ExtraData
}

// GetExtraDataOk returns a tuple with the ExtraData field value
// and a boolean to check if the value has been set.
func (o *OutputCatalogOfPattern) GetExtraDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.ExtraData, true
}

// SetExtraData sets field value
func (o *OutputCatalogOfPattern) SetExtraData(v map[string]interface{}) {
	o.ExtraData = v
}

func (o OutputCatalogOfPattern) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputCatalogOfPattern) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_id"] = o.UnderscoreId
	toSerialize["_type"] = o.UnderscoreType
	toSerialize["createdBy"] = o.CreatedBy
	toSerialize["createdAt"] = o.CreatedAt
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Variant) {
		toSerialize["variant"] = o.Variant
	}
	toSerialize["extraData"] = o.ExtraData
	return toSerialize, nil
}

func (o *OutputCatalogOfPattern) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_id",
		"_type",
		"createdBy",
		"createdAt",
		"name",
		"extraData",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputCatalogOfPattern := _OutputCatalogOfPattern{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputCatalogOfPattern)

	if err != nil {
		return err
	}

	*o = OutputCatalogOfPattern(varOutputCatalogOfPattern)

	return err
}

type NullableOutputCatalogOfPattern struct {
	value *OutputCatalogOfPattern
	isSet bool
}

func (v NullableOutputCatalogOfPattern) Get() *OutputCatalogOfPattern {
	return v.value
}

func (v *NullableOutputCatalogOfPattern) Set(val *OutputCatalogOfPattern) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputCatalogOfPattern) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputCatalogOfPattern) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputCatalogOfPattern(val *OutputCatalogOfPattern) *NullableOutputCatalogOfPattern {
	return &NullableOutputCatalogOfPattern{value: val, isSet: true}
}

func (v NullableOutputCatalogOfPattern) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputCatalogOfPattern) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
