/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ```

API version: v1-5.5.11-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InputShare type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputShare{}

// InputShare struct for InputShare
type InputShare struct {
	// Name or id of the organisation
	Organisation string `json:"organisation"`
	// If true, new observables and tasks will also be shared to the organisation
	Share *bool `json:"share,omitempty"`
	// Profile used to define the permissions of the organisation members
	Profile *string `json:"profile,omitempty"`
	// Sharing rule to apply to the tasks, can be manual or autoShare
	TaskRule *string `json:"taskRule,omitempty"`
	// Sharing rule to apply to the observables, can be manual or autoShare
	ObservableRule *string `json:"observableRule,omitempty"`
}

type _InputShare InputShare

// NewInputShare instantiates a new InputShare object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputShare(organisation string) *InputShare {
	this := InputShare{}
	this.Organisation = organisation
	var share bool = true
	this.Share = &share
	var profile string = "analyst"
	this.Profile = &profile
	var taskRule string = "Sharing rule applied on the case"
	this.TaskRule = &taskRule
	var observableRule string = "Sharing rule applied on the case"
	this.ObservableRule = &observableRule
	return &this
}

// NewInputShareWithDefaults instantiates a new InputShare object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputShareWithDefaults() *InputShare {
	this := InputShare{}
	var share bool = true
	this.Share = &share
	var profile string = "analyst"
	this.Profile = &profile
	var taskRule string = "Sharing rule applied on the case"
	this.TaskRule = &taskRule
	var observableRule string = "Sharing rule applied on the case"
	this.ObservableRule = &observableRule
	return &this
}

// GetOrganisation returns the Organisation field value
func (o *InputShare) GetOrganisation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Organisation
}

// GetOrganisationOk returns a tuple with the Organisation field value
// and a boolean to check if the value has been set.
func (o *InputShare) GetOrganisationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organisation, true
}

// SetOrganisation sets field value
func (o *InputShare) SetOrganisation(v string) {
	o.Organisation = v
}

// GetShare returns the Share field value if set, zero value otherwise.
func (o *InputShare) GetShare() bool {
	if o == nil || IsNil(o.Share) {
		var ret bool
		return ret
	}
	return *o.Share
}

// GetShareOk returns a tuple with the Share field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputShare) GetShareOk() (*bool, bool) {
	if o == nil || IsNil(o.Share) {
		return nil, false
	}
	return o.Share, true
}

// HasShare returns a boolean if a field has been set.
func (o *InputShare) HasShare() bool {
	if o != nil && !IsNil(o.Share) {
		return true
	}

	return false
}

// SetShare gets a reference to the given bool and assigns it to the Share field.
func (o *InputShare) SetShare(v bool) {
	o.Share = &v
}

// GetProfile returns the Profile field value if set, zero value otherwise.
func (o *InputShare) GetProfile() string {
	if o == nil || IsNil(o.Profile) {
		var ret string
		return ret
	}
	return *o.Profile
}

// GetProfileOk returns a tuple with the Profile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputShare) GetProfileOk() (*string, bool) {
	if o == nil || IsNil(o.Profile) {
		return nil, false
	}
	return o.Profile, true
}

// HasProfile returns a boolean if a field has been set.
func (o *InputShare) HasProfile() bool {
	if o != nil && !IsNil(o.Profile) {
		return true
	}

	return false
}

// SetProfile gets a reference to the given string and assigns it to the Profile field.
func (o *InputShare) SetProfile(v string) {
	o.Profile = &v
}

// GetTaskRule returns the TaskRule field value if set, zero value otherwise.
func (o *InputShare) GetTaskRule() string {
	if o == nil || IsNil(o.TaskRule) {
		var ret string
		return ret
	}
	return *o.TaskRule
}

// GetTaskRuleOk returns a tuple with the TaskRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputShare) GetTaskRuleOk() (*string, bool) {
	if o == nil || IsNil(o.TaskRule) {
		return nil, false
	}
	return o.TaskRule, true
}

// HasTaskRule returns a boolean if a field has been set.
func (o *InputShare) HasTaskRule() bool {
	if o != nil && !IsNil(o.TaskRule) {
		return true
	}

	return false
}

// SetTaskRule gets a reference to the given string and assigns it to the TaskRule field.
func (o *InputShare) SetTaskRule(v string) {
	o.TaskRule = &v
}

// GetObservableRule returns the ObservableRule field value if set, zero value otherwise.
func (o *InputShare) GetObservableRule() string {
	if o == nil || IsNil(o.ObservableRule) {
		var ret string
		return ret
	}
	return *o.ObservableRule
}

// GetObservableRuleOk returns a tuple with the ObservableRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputShare) GetObservableRuleOk() (*string, bool) {
	if o == nil || IsNil(o.ObservableRule) {
		return nil, false
	}
	return o.ObservableRule, true
}

// HasObservableRule returns a boolean if a field has been set.
func (o *InputShare) HasObservableRule() bool {
	if o != nil && !IsNil(o.ObservableRule) {
		return true
	}

	return false
}

// SetObservableRule gets a reference to the given string and assigns it to the ObservableRule field.
func (o *InputShare) SetObservableRule(v string) {
	o.ObservableRule = &v
}

func (o InputShare) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputShare) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organisation"] = o.Organisation
	if !IsNil(o.Share) {
		toSerialize["share"] = o.Share
	}
	if !IsNil(o.Profile) {
		toSerialize["profile"] = o.Profile
	}
	if !IsNil(o.TaskRule) {
		toSerialize["taskRule"] = o.TaskRule
	}
	if !IsNil(o.ObservableRule) {
		toSerialize["observableRule"] = o.ObservableRule
	}
	return toSerialize, nil
}

func (o *InputShare) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organisation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputShare := _InputShare{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputShare)

	if err != nil {
		return err
	}

	*o = InputShare(varInputShare)

	return err
}

type NullableInputShare struct {
	value *InputShare
	isSet bool
}

func (v NullableInputShare) Get() *InputShare {
	return v.value
}

func (v *NullableInputShare) Set(val *InputShare) {
	v.value = val
	v.isSet = true
}

func (v NullableInputShare) IsSet() bool {
	return v.isSet
}

func (v *NullableInputShare) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputShare(val *InputShare) *NullableInputShare {
	return &NullableInputShare{value: val, isSet: true}
}

func (v NullableInputShare) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputShare) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
