/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputImportCase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputImportCase{}

// OutputImportCase struct for OutputImportCase
type OutputImportCase struct {
	Case OutputCase `json:"case"`
	Observables []OutputObservable `json:"observables,omitempty"`
	Procedures []OutputProcedure `json:"procedures,omitempty"`
	// Field is present if there were some errors during import
	Errors []interface{} `json:"errors,omitempty"`
}

type _OutputImportCase OutputImportCase

// NewOutputImportCase instantiates a new OutputImportCase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputImportCase(case_ OutputCase) *OutputImportCase {
	this := OutputImportCase{}
	this.Case = case_
	return &this
}

// NewOutputImportCaseWithDefaults instantiates a new OutputImportCase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputImportCaseWithDefaults() *OutputImportCase {
	this := OutputImportCase{}
	return &this
}

// GetCase returns the Case field value
func (o *OutputImportCase) GetCase() OutputCase {
	if o == nil {
		var ret OutputCase
		return ret
	}

	return o.Case
}

// GetCaseOk returns a tuple with the Case field value
// and a boolean to check if the value has been set.
func (o *OutputImportCase) GetCaseOk() (*OutputCase, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Case, true
}

// SetCase sets field value
func (o *OutputImportCase) SetCase(v OutputCase) {
	o.Case = v
}

// GetObservables returns the Observables field value if set, zero value otherwise.
func (o *OutputImportCase) GetObservables() []OutputObservable {
	if o == nil || IsNil(o.Observables) {
		var ret []OutputObservable
		return ret
	}
	return o.Observables
}

// GetObservablesOk returns a tuple with the Observables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputImportCase) GetObservablesOk() ([]OutputObservable, bool) {
	if o == nil || IsNil(o.Observables) {
		return nil, false
	}
	return o.Observables, true
}

// HasObservables returns a boolean if a field has been set.
func (o *OutputImportCase) HasObservables() bool {
	if o != nil && !IsNil(o.Observables) {
		return true
	}

	return false
}

// SetObservables gets a reference to the given []OutputObservable and assigns it to the Observables field.
func (o *OutputImportCase) SetObservables(v []OutputObservable) {
	o.Observables = v
}

// GetProcedures returns the Procedures field value if set, zero value otherwise.
func (o *OutputImportCase) GetProcedures() []OutputProcedure {
	if o == nil || IsNil(o.Procedures) {
		var ret []OutputProcedure
		return ret
	}
	return o.Procedures
}

// GetProceduresOk returns a tuple with the Procedures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputImportCase) GetProceduresOk() ([]OutputProcedure, bool) {
	if o == nil || IsNil(o.Procedures) {
		return nil, false
	}
	return o.Procedures, true
}

// HasProcedures returns a boolean if a field has been set.
func (o *OutputImportCase) HasProcedures() bool {
	if o != nil && !IsNil(o.Procedures) {
		return true
	}

	return false
}

// SetProcedures gets a reference to the given []OutputProcedure and assigns it to the Procedures field.
func (o *OutputImportCase) SetProcedures(v []OutputProcedure) {
	o.Procedures = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *OutputImportCase) GetErrors() []interface{} {
	if o == nil || IsNil(o.Errors) {
		var ret []interface{}
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputImportCase) GetErrorsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *OutputImportCase) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []interface{} and assigns it to the Errors field.
func (o *OutputImportCase) SetErrors(v []interface{}) {
	o.Errors = v
}

func (o OutputImportCase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputImportCase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["case"] = o.Case
	if !IsNil(o.Observables) {
		toSerialize["observables"] = o.Observables
	}
	if !IsNil(o.Procedures) {
		toSerialize["procedures"] = o.Procedures
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *OutputImportCase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"case",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputImportCase := _OutputImportCase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputImportCase)

	if err != nil {
		return err
	}

	*o = OutputImportCase(varOutputImportCase)

	return err
}

type NullableOutputImportCase struct {
	value *OutputImportCase
	isSet bool
}

func (v NullableOutputImportCase) Get() *OutputImportCase {
	return v.value
}

func (v *NullableOutputImportCase) Set(val *OutputImportCase) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputImportCase) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputImportCase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputImportCase(val *OutputImportCase) *NullableOutputImportCase {
	return &NullableOutputImportCase{value: val, isSet: true}
}

func (v NullableOutputImportCase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputImportCase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


