/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputPattern type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputPattern{}

// OutputPattern struct for OutputPattern
type OutputPattern struct {
	UnderscoreId string `json:"_id"`
	UnderscoreType string `json:"_type"`
	UnderscoreCreatedBy string `json:"_createdBy"`
	UnderscoreUpdatedBy *string `json:"_updatedBy,omitempty"`
	UnderscoreCreatedAt int64 `json:"_createdAt"`
	UnderscoreUpdatedAt *int64 `json:"_updatedAt,omitempty"`
	PatternId string `json:"patternId"`
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	Tactics []string `json:"tactics,omitempty"`
	Url string `json:"url"`
	PatternType string `json:"patternType"`
	CapecId *string `json:"capecId,omitempty"`
	CapecUrl *string `json:"capecUrl,omitempty"`
	Revoked bool `json:"revoked"`
	DataSources []string `json:"dataSources,omitempty"`
	DefenseBypassed []string `json:"defenseBypassed,omitempty"`
	Detection *string `json:"detection,omitempty"`
	PermissionsRequired []string `json:"permissionsRequired,omitempty"`
	Platforms []string `json:"platforms,omitempty"`
	RemoteSupport bool `json:"remoteSupport"`
	SystemRequirements []string `json:"systemRequirements,omitempty"`
	Version *string `json:"version,omitempty"`
	ExtraData map[string]interface{} `json:"extraData"`
}

type _OutputPattern OutputPattern

// NewOutputPattern instantiates a new OutputPattern object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputPattern(underscoreId string, underscoreType string, underscoreCreatedBy string, underscoreCreatedAt int64, patternId string, name string, url string, patternType string, revoked bool, remoteSupport bool, extraData map[string]interface{}) *OutputPattern {
	this := OutputPattern{}
	this.UnderscoreId = underscoreId
	this.UnderscoreType = underscoreType
	this.UnderscoreCreatedBy = underscoreCreatedBy
	this.UnderscoreCreatedAt = underscoreCreatedAt
	this.PatternId = patternId
	this.Name = name
	this.Url = url
	this.PatternType = patternType
	this.Revoked = revoked
	this.RemoteSupport = remoteSupport
	this.ExtraData = extraData
	return &this
}

// NewOutputPatternWithDefaults instantiates a new OutputPattern object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputPatternWithDefaults() *OutputPattern {
	this := OutputPattern{}
	return &this
}

// GetUnderscoreId returns the UnderscoreId field value
func (o *OutputPattern) GetUnderscoreId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnderscoreId
}

// GetUnderscoreIdOk returns a tuple with the UnderscoreId field value
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetUnderscoreIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderscoreId, true
}

// SetUnderscoreId sets field value
func (o *OutputPattern) SetUnderscoreId(v string) {
	o.UnderscoreId = v
}

// GetUnderscoreType returns the UnderscoreType field value
func (o *OutputPattern) GetUnderscoreType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnderscoreType
}

// GetUnderscoreTypeOk returns a tuple with the UnderscoreType field value
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetUnderscoreTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderscoreType, true
}

// SetUnderscoreType sets field value
func (o *OutputPattern) SetUnderscoreType(v string) {
	o.UnderscoreType = v
}

// GetUnderscoreCreatedBy returns the UnderscoreCreatedBy field value
func (o *OutputPattern) GetUnderscoreCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnderscoreCreatedBy
}

// GetUnderscoreCreatedByOk returns a tuple with the UnderscoreCreatedBy field value
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetUnderscoreCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderscoreCreatedBy, true
}

// SetUnderscoreCreatedBy sets field value
func (o *OutputPattern) SetUnderscoreCreatedBy(v string) {
	o.UnderscoreCreatedBy = v
}

// GetUnderscoreUpdatedBy returns the UnderscoreUpdatedBy field value if set, zero value otherwise.
func (o *OutputPattern) GetUnderscoreUpdatedBy() string {
	if o == nil || IsNil(o.UnderscoreUpdatedBy) {
		var ret string
		return ret
	}
	return *o.UnderscoreUpdatedBy
}

// GetUnderscoreUpdatedByOk returns a tuple with the UnderscoreUpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetUnderscoreUpdatedByOk() (*string, bool) {
	if o == nil || IsNil(o.UnderscoreUpdatedBy) {
		return nil, false
	}
	return o.UnderscoreUpdatedBy, true
}

// HasUnderscoreUpdatedBy returns a boolean if a field has been set.
func (o *OutputPattern) HasUnderscoreUpdatedBy() bool {
	if o != nil && !IsNil(o.UnderscoreUpdatedBy) {
		return true
	}

	return false
}

// SetUnderscoreUpdatedBy gets a reference to the given string and assigns it to the UnderscoreUpdatedBy field.
func (o *OutputPattern) SetUnderscoreUpdatedBy(v string) {
	o.UnderscoreUpdatedBy = &v
}

// GetUnderscoreCreatedAt returns the UnderscoreCreatedAt field value
func (o *OutputPattern) GetUnderscoreCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UnderscoreCreatedAt
}

// GetUnderscoreCreatedAtOk returns a tuple with the UnderscoreCreatedAt field value
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetUnderscoreCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderscoreCreatedAt, true
}

// SetUnderscoreCreatedAt sets field value
func (o *OutputPattern) SetUnderscoreCreatedAt(v int64) {
	o.UnderscoreCreatedAt = v
}

// GetUnderscoreUpdatedAt returns the UnderscoreUpdatedAt field value if set, zero value otherwise.
func (o *OutputPattern) GetUnderscoreUpdatedAt() int64 {
	if o == nil || IsNil(o.UnderscoreUpdatedAt) {
		var ret int64
		return ret
	}
	return *o.UnderscoreUpdatedAt
}

// GetUnderscoreUpdatedAtOk returns a tuple with the UnderscoreUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetUnderscoreUpdatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.UnderscoreUpdatedAt) {
		return nil, false
	}
	return o.UnderscoreUpdatedAt, true
}

// HasUnderscoreUpdatedAt returns a boolean if a field has been set.
func (o *OutputPattern) HasUnderscoreUpdatedAt() bool {
	if o != nil && !IsNil(o.UnderscoreUpdatedAt) {
		return true
	}

	return false
}

// SetUnderscoreUpdatedAt gets a reference to the given int64 and assigns it to the UnderscoreUpdatedAt field.
func (o *OutputPattern) SetUnderscoreUpdatedAt(v int64) {
	o.UnderscoreUpdatedAt = &v
}

// GetPatternId returns the PatternId field value
func (o *OutputPattern) GetPatternId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PatternId
}

// GetPatternIdOk returns a tuple with the PatternId field value
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetPatternIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PatternId, true
}

// SetPatternId sets field value
func (o *OutputPattern) SetPatternId(v string) {
	o.PatternId = v
}

// GetName returns the Name field value
func (o *OutputPattern) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OutputPattern) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *OutputPattern) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *OutputPattern) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *OutputPattern) SetDescription(v string) {
	o.Description = &v
}

// GetTactics returns the Tactics field value if set, zero value otherwise.
func (o *OutputPattern) GetTactics() []string {
	if o == nil || IsNil(o.Tactics) {
		var ret []string
		return ret
	}
	return o.Tactics
}

// GetTacticsOk returns a tuple with the Tactics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetTacticsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tactics) {
		return nil, false
	}
	return o.Tactics, true
}

// HasTactics returns a boolean if a field has been set.
func (o *OutputPattern) HasTactics() bool {
	if o != nil && !IsNil(o.Tactics) {
		return true
	}

	return false
}

// SetTactics gets a reference to the given []string and assigns it to the Tactics field.
func (o *OutputPattern) SetTactics(v []string) {
	o.Tactics = v
}

// GetUrl returns the Url field value
func (o *OutputPattern) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *OutputPattern) SetUrl(v string) {
	o.Url = v
}

// GetPatternType returns the PatternType field value
func (o *OutputPattern) GetPatternType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PatternType
}

// GetPatternTypeOk returns a tuple with the PatternType field value
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetPatternTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PatternType, true
}

// SetPatternType sets field value
func (o *OutputPattern) SetPatternType(v string) {
	o.PatternType = v
}

// GetCapecId returns the CapecId field value if set, zero value otherwise.
func (o *OutputPattern) GetCapecId() string {
	if o == nil || IsNil(o.CapecId) {
		var ret string
		return ret
	}
	return *o.CapecId
}

// GetCapecIdOk returns a tuple with the CapecId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetCapecIdOk() (*string, bool) {
	if o == nil || IsNil(o.CapecId) {
		return nil, false
	}
	return o.CapecId, true
}

// HasCapecId returns a boolean if a field has been set.
func (o *OutputPattern) HasCapecId() bool {
	if o != nil && !IsNil(o.CapecId) {
		return true
	}

	return false
}

// SetCapecId gets a reference to the given string and assigns it to the CapecId field.
func (o *OutputPattern) SetCapecId(v string) {
	o.CapecId = &v
}

// GetCapecUrl returns the CapecUrl field value if set, zero value otherwise.
func (o *OutputPattern) GetCapecUrl() string {
	if o == nil || IsNil(o.CapecUrl) {
		var ret string
		return ret
	}
	return *o.CapecUrl
}

// GetCapecUrlOk returns a tuple with the CapecUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetCapecUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CapecUrl) {
		return nil, false
	}
	return o.CapecUrl, true
}

// HasCapecUrl returns a boolean if a field has been set.
func (o *OutputPattern) HasCapecUrl() bool {
	if o != nil && !IsNil(o.CapecUrl) {
		return true
	}

	return false
}

// SetCapecUrl gets a reference to the given string and assigns it to the CapecUrl field.
func (o *OutputPattern) SetCapecUrl(v string) {
	o.CapecUrl = &v
}

// GetRevoked returns the Revoked field value
func (o *OutputPattern) GetRevoked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Revoked
}

// GetRevokedOk returns a tuple with the Revoked field value
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetRevokedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revoked, true
}

// SetRevoked sets field value
func (o *OutputPattern) SetRevoked(v bool) {
	o.Revoked = v
}

// GetDataSources returns the DataSources field value if set, zero value otherwise.
func (o *OutputPattern) GetDataSources() []string {
	if o == nil || IsNil(o.DataSources) {
		var ret []string
		return ret
	}
	return o.DataSources
}

// GetDataSourcesOk returns a tuple with the DataSources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetDataSourcesOk() ([]string, bool) {
	if o == nil || IsNil(o.DataSources) {
		return nil, false
	}
	return o.DataSources, true
}

// HasDataSources returns a boolean if a field has been set.
func (o *OutputPattern) HasDataSources() bool {
	if o != nil && !IsNil(o.DataSources) {
		return true
	}

	return false
}

// SetDataSources gets a reference to the given []string and assigns it to the DataSources field.
func (o *OutputPattern) SetDataSources(v []string) {
	o.DataSources = v
}

// GetDefenseBypassed returns the DefenseBypassed field value if set, zero value otherwise.
func (o *OutputPattern) GetDefenseBypassed() []string {
	if o == nil || IsNil(o.DefenseBypassed) {
		var ret []string
		return ret
	}
	return o.DefenseBypassed
}

// GetDefenseBypassedOk returns a tuple with the DefenseBypassed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetDefenseBypassedOk() ([]string, bool) {
	if o == nil || IsNil(o.DefenseBypassed) {
		return nil, false
	}
	return o.DefenseBypassed, true
}

// HasDefenseBypassed returns a boolean if a field has been set.
func (o *OutputPattern) HasDefenseBypassed() bool {
	if o != nil && !IsNil(o.DefenseBypassed) {
		return true
	}

	return false
}

// SetDefenseBypassed gets a reference to the given []string and assigns it to the DefenseBypassed field.
func (o *OutputPattern) SetDefenseBypassed(v []string) {
	o.DefenseBypassed = v
}

// GetDetection returns the Detection field value if set, zero value otherwise.
func (o *OutputPattern) GetDetection() string {
	if o == nil || IsNil(o.Detection) {
		var ret string
		return ret
	}
	return *o.Detection
}

// GetDetectionOk returns a tuple with the Detection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetDetectionOk() (*string, bool) {
	if o == nil || IsNil(o.Detection) {
		return nil, false
	}
	return o.Detection, true
}

// HasDetection returns a boolean if a field has been set.
func (o *OutputPattern) HasDetection() bool {
	if o != nil && !IsNil(o.Detection) {
		return true
	}

	return false
}

// SetDetection gets a reference to the given string and assigns it to the Detection field.
func (o *OutputPattern) SetDetection(v string) {
	o.Detection = &v
}

// GetPermissionsRequired returns the PermissionsRequired field value if set, zero value otherwise.
func (o *OutputPattern) GetPermissionsRequired() []string {
	if o == nil || IsNil(o.PermissionsRequired) {
		var ret []string
		return ret
	}
	return o.PermissionsRequired
}

// GetPermissionsRequiredOk returns a tuple with the PermissionsRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetPermissionsRequiredOk() ([]string, bool) {
	if o == nil || IsNil(o.PermissionsRequired) {
		return nil, false
	}
	return o.PermissionsRequired, true
}

// HasPermissionsRequired returns a boolean if a field has been set.
func (o *OutputPattern) HasPermissionsRequired() bool {
	if o != nil && !IsNil(o.PermissionsRequired) {
		return true
	}

	return false
}

// SetPermissionsRequired gets a reference to the given []string and assigns it to the PermissionsRequired field.
func (o *OutputPattern) SetPermissionsRequired(v []string) {
	o.PermissionsRequired = v
}

// GetPlatforms returns the Platforms field value if set, zero value otherwise.
func (o *OutputPattern) GetPlatforms() []string {
	if o == nil || IsNil(o.Platforms) {
		var ret []string
		return ret
	}
	return o.Platforms
}

// GetPlatformsOk returns a tuple with the Platforms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetPlatformsOk() ([]string, bool) {
	if o == nil || IsNil(o.Platforms) {
		return nil, false
	}
	return o.Platforms, true
}

// HasPlatforms returns a boolean if a field has been set.
func (o *OutputPattern) HasPlatforms() bool {
	if o != nil && !IsNil(o.Platforms) {
		return true
	}

	return false
}

// SetPlatforms gets a reference to the given []string and assigns it to the Platforms field.
func (o *OutputPattern) SetPlatforms(v []string) {
	o.Platforms = v
}

// GetRemoteSupport returns the RemoteSupport field value
func (o *OutputPattern) GetRemoteSupport() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RemoteSupport
}

// GetRemoteSupportOk returns a tuple with the RemoteSupport field value
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetRemoteSupportOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemoteSupport, true
}

// SetRemoteSupport sets field value
func (o *OutputPattern) SetRemoteSupport(v bool) {
	o.RemoteSupport = v
}

// GetSystemRequirements returns the SystemRequirements field value if set, zero value otherwise.
func (o *OutputPattern) GetSystemRequirements() []string {
	if o == nil || IsNil(o.SystemRequirements) {
		var ret []string
		return ret
	}
	return o.SystemRequirements
}

// GetSystemRequirementsOk returns a tuple with the SystemRequirements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetSystemRequirementsOk() ([]string, bool) {
	if o == nil || IsNil(o.SystemRequirements) {
		return nil, false
	}
	return o.SystemRequirements, true
}

// HasSystemRequirements returns a boolean if a field has been set.
func (o *OutputPattern) HasSystemRequirements() bool {
	if o != nil && !IsNil(o.SystemRequirements) {
		return true
	}

	return false
}

// SetSystemRequirements gets a reference to the given []string and assigns it to the SystemRequirements field.
func (o *OutputPattern) SetSystemRequirements(v []string) {
	o.SystemRequirements = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *OutputPattern) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *OutputPattern) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *OutputPattern) SetVersion(v string) {
	o.Version = &v
}

// GetExtraData returns the ExtraData field value
func (o *OutputPattern) GetExtraData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ExtraData
}

// GetExtraDataOk returns a tuple with the ExtraData field value
// and a boolean to check if the value has been set.
func (o *OutputPattern) GetExtraDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.ExtraData, true
}

// SetExtraData sets field value
func (o *OutputPattern) SetExtraData(v map[string]interface{}) {
	o.ExtraData = v
}

func (o OutputPattern) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputPattern) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_id"] = o.UnderscoreId
	toSerialize["_type"] = o.UnderscoreType
	toSerialize["_createdBy"] = o.UnderscoreCreatedBy
	if !IsNil(o.UnderscoreUpdatedBy) {
		toSerialize["_updatedBy"] = o.UnderscoreUpdatedBy
	}
	toSerialize["_createdAt"] = o.UnderscoreCreatedAt
	if !IsNil(o.UnderscoreUpdatedAt) {
		toSerialize["_updatedAt"] = o.UnderscoreUpdatedAt
	}
	toSerialize["patternId"] = o.PatternId
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Tactics) {
		toSerialize["tactics"] = o.Tactics
	}
	toSerialize["url"] = o.Url
	toSerialize["patternType"] = o.PatternType
	if !IsNil(o.CapecId) {
		toSerialize["capecId"] = o.CapecId
	}
	if !IsNil(o.CapecUrl) {
		toSerialize["capecUrl"] = o.CapecUrl
	}
	toSerialize["revoked"] = o.Revoked
	if !IsNil(o.DataSources) {
		toSerialize["dataSources"] = o.DataSources
	}
	if !IsNil(o.DefenseBypassed) {
		toSerialize["defenseBypassed"] = o.DefenseBypassed
	}
	if !IsNil(o.Detection) {
		toSerialize["detection"] = o.Detection
	}
	if !IsNil(o.PermissionsRequired) {
		toSerialize["permissionsRequired"] = o.PermissionsRequired
	}
	if !IsNil(o.Platforms) {
		toSerialize["platforms"] = o.Platforms
	}
	toSerialize["remoteSupport"] = o.RemoteSupport
	if !IsNil(o.SystemRequirements) {
		toSerialize["systemRequirements"] = o.SystemRequirements
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	toSerialize["extraData"] = o.ExtraData
	return toSerialize, nil
}

func (o *OutputPattern) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_id",
		"_type",
		"_createdBy",
		"_createdAt",
		"patternId",
		"name",
		"url",
		"patternType",
		"revoked",
		"remoteSupport",
		"extraData",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputPattern := _OutputPattern{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputPattern)

	if err != nil {
		return err
	}

	*o = OutputPattern(varOutputPattern)

	return err
}

type NullableOutputPattern struct {
	value *OutputPattern
	isSet bool
}

func (v NullableOutputPattern) Get() *OutputPattern {
	return v.value
}

func (v *NullableOutputPattern) Set(val *OutputPattern) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputPattern) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputPattern) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputPattern(val *OutputPattern) *NullableOutputPattern {
	return &NullableOutputPattern{value: val, isSet: true}
}

func (v NullableOutputPattern) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputPattern) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


