/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ```

API version: v1-5.5.11-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InputEmailIntakeConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputEmailIntakeConfig{}

// InputEmailIntakeConfig struct for InputEmailIntakeConfig
type InputEmailIntakeConfig struct {
	Id      *string                       `json:"id,omitempty"`
	Name    string                        `json:"name"`
	Mailbox InputEmailIntakeMailboxConfig `json:"mailbox"`
	// At least one organisation
	Organisations   []string                         `json:"organisations,omitempty"`
	Enabled         *bool                            `json:"enabled,omitempty"`
	CreatedAt       *int64                           `json:"createdAt,omitempty"`
	AlertProperties *InputEmailIntakeAlertProperties `json:"alertProperties,omitempty"`
}

type _InputEmailIntakeConfig InputEmailIntakeConfig

// NewInputEmailIntakeConfig instantiates a new InputEmailIntakeConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputEmailIntakeConfig(name string, mailbox InputEmailIntakeMailboxConfig) *InputEmailIntakeConfig {
	this := InputEmailIntakeConfig{}
	this.Name = name
	this.Mailbox = mailbox
	var enabled bool = true
	this.Enabled = &enabled
	return &this
}

// NewInputEmailIntakeConfigWithDefaults instantiates a new InputEmailIntakeConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputEmailIntakeConfigWithDefaults() *InputEmailIntakeConfig {
	this := InputEmailIntakeConfig{}
	var enabled bool = true
	this.Enabled = &enabled
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InputEmailIntakeConfig) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputEmailIntakeConfig) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InputEmailIntakeConfig) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InputEmailIntakeConfig) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *InputEmailIntakeConfig) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InputEmailIntakeConfig) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InputEmailIntakeConfig) SetName(v string) {
	o.Name = v
}

// GetMailbox returns the Mailbox field value
func (o *InputEmailIntakeConfig) GetMailbox() InputEmailIntakeMailboxConfig {
	if o == nil {
		var ret InputEmailIntakeMailboxConfig
		return ret
	}

	return o.Mailbox
}

// GetMailboxOk returns a tuple with the Mailbox field value
// and a boolean to check if the value has been set.
func (o *InputEmailIntakeConfig) GetMailboxOk() (*InputEmailIntakeMailboxConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mailbox, true
}

// SetMailbox sets field value
func (o *InputEmailIntakeConfig) SetMailbox(v InputEmailIntakeMailboxConfig) {
	o.Mailbox = v
}

// GetOrganisations returns the Organisations field value if set, zero value otherwise.
func (o *InputEmailIntakeConfig) GetOrganisations() []string {
	if o == nil || IsNil(o.Organisations) {
		var ret []string
		return ret
	}
	return o.Organisations
}

// GetOrganisationsOk returns a tuple with the Organisations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputEmailIntakeConfig) GetOrganisationsOk() ([]string, bool) {
	if o == nil || IsNil(o.Organisations) {
		return nil, false
	}
	return o.Organisations, true
}

// HasOrganisations returns a boolean if a field has been set.
func (o *InputEmailIntakeConfig) HasOrganisations() bool {
	if o != nil && !IsNil(o.Organisations) {
		return true
	}

	return false
}

// SetOrganisations gets a reference to the given []string and assigns it to the Organisations field.
func (o *InputEmailIntakeConfig) SetOrganisations(v []string) {
	o.Organisations = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *InputEmailIntakeConfig) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputEmailIntakeConfig) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *InputEmailIntakeConfig) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *InputEmailIntakeConfig) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *InputEmailIntakeConfig) GetCreatedAt() int64 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputEmailIntakeConfig) GetCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *InputEmailIntakeConfig) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *InputEmailIntakeConfig) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetAlertProperties returns the AlertProperties field value if set, zero value otherwise.
func (o *InputEmailIntakeConfig) GetAlertProperties() InputEmailIntakeAlertProperties {
	if o == nil || IsNil(o.AlertProperties) {
		var ret InputEmailIntakeAlertProperties
		return ret
	}
	return *o.AlertProperties
}

// GetAlertPropertiesOk returns a tuple with the AlertProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputEmailIntakeConfig) GetAlertPropertiesOk() (*InputEmailIntakeAlertProperties, bool) {
	if o == nil || IsNil(o.AlertProperties) {
		return nil, false
	}
	return o.AlertProperties, true
}

// HasAlertProperties returns a boolean if a field has been set.
func (o *InputEmailIntakeConfig) HasAlertProperties() bool {
	if o != nil && !IsNil(o.AlertProperties) {
		return true
	}

	return false
}

// SetAlertProperties gets a reference to the given InputEmailIntakeAlertProperties and assigns it to the AlertProperties field.
func (o *InputEmailIntakeConfig) SetAlertProperties(v InputEmailIntakeAlertProperties) {
	o.AlertProperties = &v
}

func (o InputEmailIntakeConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputEmailIntakeConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	toSerialize["mailbox"] = o.Mailbox
	if !IsNil(o.Organisations) {
		toSerialize["organisations"] = o.Organisations
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.AlertProperties) {
		toSerialize["alertProperties"] = o.AlertProperties
	}
	return toSerialize, nil
}

func (o *InputEmailIntakeConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"mailbox",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputEmailIntakeConfig := _InputEmailIntakeConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputEmailIntakeConfig)

	if err != nil {
		return err
	}

	*o = InputEmailIntakeConfig(varInputEmailIntakeConfig)

	return err
}

type NullableInputEmailIntakeConfig struct {
	value *InputEmailIntakeConfig
	isSet bool
}

func (v NullableInputEmailIntakeConfig) Get() *InputEmailIntakeConfig {
	return v.value
}

func (v *NullableInputEmailIntakeConfig) Set(val *InputEmailIntakeConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableInputEmailIntakeConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableInputEmailIntakeConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputEmailIntakeConfig(val *InputEmailIntakeConfig) *NullableInputEmailIntakeConfig {
	return &NullableInputEmailIntakeConfig{value: val, isSet: true}
}

func (v NullableInputEmailIntakeConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputEmailIntakeConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
