/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ```

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InputAttachment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputAttachment{}

// InputAttachment existing attachment in TheHive
type InputAttachment struct {
	Name        string `json:"name"`
	ContentType string `json:"contentType"`
	Id          string `json:"id"`
}

type _InputAttachment InputAttachment

// NewInputAttachment instantiates a new InputAttachment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputAttachment(name string, contentType string, id string) *InputAttachment {
	this := InputAttachment{}
	this.Name = name
	this.ContentType = contentType
	this.Id = id
	return &this
}

// NewInputAttachmentWithDefaults instantiates a new InputAttachment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputAttachmentWithDefaults() *InputAttachment {
	this := InputAttachment{}
	return &this
}

// GetName returns the Name field value
func (o *InputAttachment) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InputAttachment) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InputAttachment) SetName(v string) {
	o.Name = v
}

// GetContentType returns the ContentType field value
func (o *InputAttachment) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *InputAttachment) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *InputAttachment) SetContentType(v string) {
	o.ContentType = v
}

// GetId returns the Id field value
func (o *InputAttachment) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InputAttachment) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InputAttachment) SetId(v string) {
	o.Id = v
}

func (o InputAttachment) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputAttachment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["contentType"] = o.ContentType
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *InputAttachment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"contentType",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputAttachment := _InputAttachment{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputAttachment)

	if err != nil {
		return err
	}

	*o = InputAttachment(varInputAttachment)

	return err
}

type NullableInputAttachment struct {
	value *InputAttachment
	isSet bool
}

func (v NullableInputAttachment) Get() *InputAttachment {
	return v.value
}

func (v *NullableInputAttachment) Set(val *InputAttachment) {
	v.value = val
	v.isSet = true
}

func (v NullableInputAttachment) IsSet() bool {
	return v.isSet
}

func (v *NullableInputAttachment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputAttachment(val *InputAttachment) *NullableInputAttachment {
	return &NullableInputAttachment{value: val, isSet: true}
}

func (v NullableInputAttachment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputAttachment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
