/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v5.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// OutputInvokeFunction - struct for OutputInvokeFunction
type OutputInvokeFunction struct {
	OutputInvokeFunctionKo *OutputInvokeFunctionKo
	OutputInvokeFunctionOk *OutputInvokeFunctionOk
	MapmapOfStringAny *map[string]interface{}
}

// OutputInvokeFunctionKoAsOutputInvokeFunction is a convenience function that returns OutputInvokeFunctionKo wrapped in OutputInvokeFunction
func OutputInvokeFunctionKoAsOutputInvokeFunction(v *OutputInvokeFunctionKo) OutputInvokeFunction {
	return OutputInvokeFunction{
		OutputInvokeFunctionKo: v,
	}
}

// OutputInvokeFunctionOkAsOutputInvokeFunction is a convenience function that returns OutputInvokeFunctionOk wrapped in OutputInvokeFunction
func OutputInvokeFunctionOkAsOutputInvokeFunction(v *OutputInvokeFunctionOk) OutputInvokeFunction {
	return OutputInvokeFunction{
		OutputInvokeFunctionOk: v,
	}
}

// map[string]interface{}AsOutputInvokeFunction is a convenience function that returns map[string]interface{} wrapped in OutputInvokeFunction
func MapmapOfStringAnyAsOutputInvokeFunction(v *map[string]interface{}) OutputInvokeFunction {
	return OutputInvokeFunction{
		MapmapOfStringAny: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *OutputInvokeFunction) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into OutputInvokeFunctionKo
	err = newStrictDecoder(data).Decode(&dst.OutputInvokeFunctionKo)
	if err == nil {
		jsonOutputInvokeFunctionKo, _ := json.Marshal(dst.OutputInvokeFunctionKo)
		if string(jsonOutputInvokeFunctionKo) == "{}" { // empty struct
			dst.OutputInvokeFunctionKo = nil
		} else {
			if err = validator.Validate(dst.OutputInvokeFunctionKo); err != nil {
				dst.OutputInvokeFunctionKo = nil
			} else {
				match++
			}
		}
	} else {
		dst.OutputInvokeFunctionKo = nil
	}

	// try to unmarshal data into OutputInvokeFunctionOk
	err = newStrictDecoder(data).Decode(&dst.OutputInvokeFunctionOk)
	if err == nil {
		jsonOutputInvokeFunctionOk, _ := json.Marshal(dst.OutputInvokeFunctionOk)
		if string(jsonOutputInvokeFunctionOk) == "{}" { // empty struct
			dst.OutputInvokeFunctionOk = nil
		} else {
			if err = validator.Validate(dst.OutputInvokeFunctionOk); err != nil {
				dst.OutputInvokeFunctionOk = nil
			} else {
				match++
			}
		}
	} else {
		dst.OutputInvokeFunctionOk = nil
	}

	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.OutputInvokeFunctionKo = nil
		dst.OutputInvokeFunctionOk = nil
		dst.MapmapOfStringAny = nil

		return fmt.Errorf("data matches more than one schema in oneOf(OutputInvokeFunction)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(OutputInvokeFunction)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src OutputInvokeFunction) MarshalJSON() ([]byte, error) {
	if src.OutputInvokeFunctionKo != nil {
		return json.Marshal(&src.OutputInvokeFunctionKo)
	}

	if src.OutputInvokeFunctionOk != nil {
		return json.Marshal(&src.OutputInvokeFunctionOk)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *OutputInvokeFunction) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.OutputInvokeFunctionKo != nil {
		return obj.OutputInvokeFunctionKo
	}

	if obj.OutputInvokeFunctionOk != nil {
		return obj.OutputInvokeFunctionOk
	}

	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj OutputInvokeFunction) GetActualInstanceValue() (interface{}) {
	if obj.OutputInvokeFunctionKo != nil {
		return *obj.OutputInvokeFunctionKo
	}

	if obj.OutputInvokeFunctionOk != nil {
		return *obj.OutputInvokeFunctionOk
	}

	if obj.MapmapOfStringAny != nil {
		return *obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

type NullableOutputInvokeFunction struct {
	value *OutputInvokeFunction
	isSet bool
}

func (v NullableOutputInvokeFunction) Get() *OutputInvokeFunction {
	return v.value
}

func (v *NullableOutputInvokeFunction) Set(val *OutputInvokeFunction) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputInvokeFunction) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputInvokeFunction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputInvokeFunction(val *OutputInvokeFunction) *NullableOutputInvokeFunction {
	return &NullableOutputInvokeFunction{value: val, isSet: true}
}

func (v NullableOutputInvokeFunction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputInvokeFunction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


