/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StoreConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoreConfig{}

// StoreConfig struct for StoreConfig
type StoreConfig struct {
	Data *string `json:"data,omitempty"`
	FilePath *string `json:"filePath,omitempty"`
	IsFileOnClasspath *bool `json:"isFileOnClasspath,omitempty"`
	Password *string `json:"password,omitempty"`
	Type string `json:"type"`
}

type _StoreConfig StoreConfig

// NewStoreConfig instantiates a new StoreConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreConfig(type_ string) *StoreConfig {
	this := StoreConfig{}
	var isFileOnClasspath bool = false
	this.IsFileOnClasspath = &isFileOnClasspath
	this.Type = type_
	return &this
}

// NewStoreConfigWithDefaults instantiates a new StoreConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreConfigWithDefaults() *StoreConfig {
	this := StoreConfig{}
	var isFileOnClasspath bool = false
	this.IsFileOnClasspath = &isFileOnClasspath
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *StoreConfig) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreConfig) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *StoreConfig) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *StoreConfig) SetData(v string) {
	o.Data = &v
}

// GetFilePath returns the FilePath field value if set, zero value otherwise.
func (o *StoreConfig) GetFilePath() string {
	if o == nil || IsNil(o.FilePath) {
		var ret string
		return ret
	}
	return *o.FilePath
}

// GetFilePathOk returns a tuple with the FilePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreConfig) GetFilePathOk() (*string, bool) {
	if o == nil || IsNil(o.FilePath) {
		return nil, false
	}
	return o.FilePath, true
}

// HasFilePath returns a boolean if a field has been set.
func (o *StoreConfig) HasFilePath() bool {
	if o != nil && !IsNil(o.FilePath) {
		return true
	}

	return false
}

// SetFilePath gets a reference to the given string and assigns it to the FilePath field.
func (o *StoreConfig) SetFilePath(v string) {
	o.FilePath = &v
}

// GetIsFileOnClasspath returns the IsFileOnClasspath field value if set, zero value otherwise.
func (o *StoreConfig) GetIsFileOnClasspath() bool {
	if o == nil || IsNil(o.IsFileOnClasspath) {
		var ret bool
		return ret
	}
	return *o.IsFileOnClasspath
}

// GetIsFileOnClasspathOk returns a tuple with the IsFileOnClasspath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreConfig) GetIsFileOnClasspathOk() (*bool, bool) {
	if o == nil || IsNil(o.IsFileOnClasspath) {
		return nil, false
	}
	return o.IsFileOnClasspath, true
}

// HasIsFileOnClasspath returns a boolean if a field has been set.
func (o *StoreConfig) HasIsFileOnClasspath() bool {
	if o != nil && !IsNil(o.IsFileOnClasspath) {
		return true
	}

	return false
}

// SetIsFileOnClasspath gets a reference to the given bool and assigns it to the IsFileOnClasspath field.
func (o *StoreConfig) SetIsFileOnClasspath(v bool) {
	o.IsFileOnClasspath = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *StoreConfig) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreConfig) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *StoreConfig) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *StoreConfig) SetPassword(v string) {
	o.Password = &v
}

// GetType returns the Type field value
func (o *StoreConfig) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *StoreConfig) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *StoreConfig) SetType(v string) {
	o.Type = v
}

func (o StoreConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoreConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.FilePath) {
		toSerialize["filePath"] = o.FilePath
	}
	if !IsNil(o.IsFileOnClasspath) {
		toSerialize["isFileOnClasspath"] = o.IsFileOnClasspath
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *StoreConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoreConfig := _StoreConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStoreConfig)

	if err != nil {
		return err
	}

	*o = StoreConfig(varStoreConfig)

	return err
}

type NullableStoreConfig struct {
	value *StoreConfig
	isSet bool
}

func (v NullableStoreConfig) Get() *StoreConfig {
	return v.value
}

func (v *NullableStoreConfig) Set(val *StoreConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreConfig(val *StoreConfig) *NullableStoreConfig {
	return &NullableStoreConfig{value: val, isSet: true}
}

func (v NullableStoreConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


