/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ```

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InputCaseLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputCaseLink{}

// InputCaseLink struct for InputCaseLink
type InputCaseLink struct {
	Type   string `json:"type"`
	CaseId string `json:"caseId"`
}

type _InputCaseLink InputCaseLink

// NewInputCaseLink instantiates a new InputCaseLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputCaseLink(type_ string, caseId string) *InputCaseLink {
	this := InputCaseLink{}
	this.Type = type_
	this.CaseId = caseId
	return &this
}

// NewInputCaseLinkWithDefaults instantiates a new InputCaseLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputCaseLinkWithDefaults() *InputCaseLink {
	this := InputCaseLink{}
	return &this
}

// GetType returns the Type field value
func (o *InputCaseLink) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InputCaseLink) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InputCaseLink) SetType(v string) {
	o.Type = v
}

// GetCaseId returns the CaseId field value
func (o *InputCaseLink) GetCaseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CaseId
}

// GetCaseIdOk returns a tuple with the CaseId field value
// and a boolean to check if the value has been set.
func (o *InputCaseLink) GetCaseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CaseId, true
}

// SetCaseId sets field value
func (o *InputCaseLink) SetCaseId(v string) {
	o.CaseId = v
}

func (o InputCaseLink) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputCaseLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["caseId"] = o.CaseId
	return toSerialize, nil
}

func (o *InputCaseLink) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"caseId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputCaseLink := _InputCaseLink{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputCaseLink)

	if err != nil {
		return err
	}

	*o = InputCaseLink(varInputCaseLink)

	return err
}

type NullableInputCaseLink struct {
	value *InputCaseLink
	isSet bool
}

func (v NullableInputCaseLink) Get() *InputCaseLink {
	return v.value
}

func (v *NullableInputCaseLink) Set(val *InputCaseLink) {
	v.value = val
	v.isSet = true
}

func (v NullableInputCaseLink) IsSet() bool {
	return v.isSet
}

func (v *NullableInputCaseLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputCaseLink(val *InputCaseLink) *NullableInputCaseLink {
	return &NullableInputCaseLink{value: val, isSet: true}
}

func (v NullableInputCaseLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputCaseLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
