/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IntegerPropertyDescription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegerPropertyDescription{}

// IntegerPropertyDescription struct for IntegerPropertyDescription
type IntegerPropertyDescription struct {
	Name string `json:"name"`
	Cardinality Cardinality `json:"cardinality"`
	Aggregable bool `json:"aggregable"`
	IndexType BasicIndexType `json:"indexType"`
	Type string `json:"type"`
}

type _IntegerPropertyDescription IntegerPropertyDescription

// NewIntegerPropertyDescription instantiates a new IntegerPropertyDescription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegerPropertyDescription(name string, cardinality Cardinality, aggregable bool, indexType BasicIndexType, type_ string) *IntegerPropertyDescription {
	this := IntegerPropertyDescription{}
	this.Name = name
	this.Cardinality = cardinality
	this.Aggregable = aggregable
	this.IndexType = indexType
	this.Type = type_
	return &this
}

// NewIntegerPropertyDescriptionWithDefaults instantiates a new IntegerPropertyDescription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegerPropertyDescriptionWithDefaults() *IntegerPropertyDescription {
	this := IntegerPropertyDescription{}
	return &this
}

// GetName returns the Name field value
func (o *IntegerPropertyDescription) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *IntegerPropertyDescription) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *IntegerPropertyDescription) SetName(v string) {
	o.Name = v
}

// GetCardinality returns the Cardinality field value
func (o *IntegerPropertyDescription) GetCardinality() Cardinality {
	if o == nil {
		var ret Cardinality
		return ret
	}

	return o.Cardinality
}

// GetCardinalityOk returns a tuple with the Cardinality field value
// and a boolean to check if the value has been set.
func (o *IntegerPropertyDescription) GetCardinalityOk() (*Cardinality, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cardinality, true
}

// SetCardinality sets field value
func (o *IntegerPropertyDescription) SetCardinality(v Cardinality) {
	o.Cardinality = v
}

// GetAggregable returns the Aggregable field value
func (o *IntegerPropertyDescription) GetAggregable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Aggregable
}

// GetAggregableOk returns a tuple with the Aggregable field value
// and a boolean to check if the value has been set.
func (o *IntegerPropertyDescription) GetAggregableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aggregable, true
}

// SetAggregable sets field value
func (o *IntegerPropertyDescription) SetAggregable(v bool) {
	o.Aggregable = v
}

// GetIndexType returns the IndexType field value
func (o *IntegerPropertyDescription) GetIndexType() BasicIndexType {
	if o == nil {
		var ret BasicIndexType
		return ret
	}

	return o.IndexType
}

// GetIndexTypeOk returns a tuple with the IndexType field value
// and a boolean to check if the value has been set.
func (o *IntegerPropertyDescription) GetIndexTypeOk() (*BasicIndexType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexType, true
}

// SetIndexType sets field value
func (o *IntegerPropertyDescription) SetIndexType(v BasicIndexType) {
	o.IndexType = v
}

// GetType returns the Type field value
func (o *IntegerPropertyDescription) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *IntegerPropertyDescription) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *IntegerPropertyDescription) SetType(v string) {
	o.Type = v
}

func (o IntegerPropertyDescription) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegerPropertyDescription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["cardinality"] = o.Cardinality
	toSerialize["aggregable"] = o.Aggregable
	toSerialize["indexType"] = o.IndexType
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *IntegerPropertyDescription) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"cardinality",
		"aggregable",
		"indexType",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntegerPropertyDescription := _IntegerPropertyDescription{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIntegerPropertyDescription)

	if err != nil {
		return err
	}

	*o = IntegerPropertyDescription(varIntegerPropertyDescription)

	return err
}

type NullableIntegerPropertyDescription struct {
	value *IntegerPropertyDescription
	isSet bool
}

func (v NullableIntegerPropertyDescription) Get() *IntegerPropertyDescription {
	return v.value
}

func (v *NullableIntegerPropertyDescription) Set(val *IntegerPropertyDescription) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegerPropertyDescription) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegerPropertyDescription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegerPropertyDescription(val *IntegerPropertyDescription) *NullableIntegerPropertyDescription {
	return &NullableIntegerPropertyDescription{value: val, isSet: true}
}

func (v NullableIntegerPropertyDescription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegerPropertyDescription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


