/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ```

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InputCreateCaseReportTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputCreateCaseReportTemplate{}

// InputCreateCaseReportTemplate struct for InputCreateCaseReportTemplate
type InputCreateCaseReportTemplate struct {
	Title       string                       `json:"title"`
	Group       *string                      `json:"group,omitempty"`
	Description *string                      `json:"description,omitempty"`
	Definition  CaseReportTemplateDefinition `json:"definition"`
	Version     *int32                       `json:"version,omitempty"`
}

type _InputCreateCaseReportTemplate InputCreateCaseReportTemplate

// NewInputCreateCaseReportTemplate instantiates a new InputCreateCaseReportTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputCreateCaseReportTemplate(title string, definition CaseReportTemplateDefinition) *InputCreateCaseReportTemplate {
	this := InputCreateCaseReportTemplate{}
	this.Title = title
	this.Definition = definition
	return &this
}

// NewInputCreateCaseReportTemplateWithDefaults instantiates a new InputCreateCaseReportTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputCreateCaseReportTemplateWithDefaults() *InputCreateCaseReportTemplate {
	this := InputCreateCaseReportTemplate{}
	return &this
}

// GetTitle returns the Title field value
func (o *InputCreateCaseReportTemplate) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *InputCreateCaseReportTemplate) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *InputCreateCaseReportTemplate) SetTitle(v string) {
	o.Title = v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *InputCreateCaseReportTemplate) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputCreateCaseReportTemplate) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *InputCreateCaseReportTemplate) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *InputCreateCaseReportTemplate) SetGroup(v string) {
	o.Group = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InputCreateCaseReportTemplate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputCreateCaseReportTemplate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InputCreateCaseReportTemplate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InputCreateCaseReportTemplate) SetDescription(v string) {
	o.Description = &v
}

// GetDefinition returns the Definition field value
func (o *InputCreateCaseReportTemplate) GetDefinition() CaseReportTemplateDefinition {
	if o == nil {
		var ret CaseReportTemplateDefinition
		return ret
	}

	return o.Definition
}

// GetDefinitionOk returns a tuple with the Definition field value
// and a boolean to check if the value has been set.
func (o *InputCreateCaseReportTemplate) GetDefinitionOk() (*CaseReportTemplateDefinition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Definition, true
}

// SetDefinition sets field value
func (o *InputCreateCaseReportTemplate) SetDefinition(v CaseReportTemplateDefinition) {
	o.Definition = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *InputCreateCaseReportTemplate) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputCreateCaseReportTemplate) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *InputCreateCaseReportTemplate) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *InputCreateCaseReportTemplate) SetVersion(v int32) {
	o.Version = &v
}

func (o InputCreateCaseReportTemplate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputCreateCaseReportTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["definition"] = o.Definition
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

func (o *InputCreateCaseReportTemplate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"definition",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputCreateCaseReportTemplate := _InputCreateCaseReportTemplate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputCreateCaseReportTemplate)

	if err != nil {
		return err
	}

	*o = InputCreateCaseReportTemplate(varInputCreateCaseReportTemplate)

	return err
}

type NullableInputCreateCaseReportTemplate struct {
	value *InputCreateCaseReportTemplate
	isSet bool
}

func (v NullableInputCreateCaseReportTemplate) Get() *InputCreateCaseReportTemplate {
	return v.value
}

func (v *NullableInputCreateCaseReportTemplate) Set(val *InputCreateCaseReportTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableInputCreateCaseReportTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableInputCreateCaseReportTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputCreateCaseReportTemplate(val *InputCreateCaseReportTemplate) *NullableInputCreateCaseReportTemplate {
	return &NullableInputCreateCaseReportTemplate{value: val, isSet: true}
}

func (v NullableInputCreateCaseReportTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputCreateCaseReportTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
