/*
TheHive

 ## General  Almost all of the endpoints will require an authentication. Supported ways of authentication are detailed below.  Each user has permissions, defined by their role. The permissions of the user are checked when making api calls.    Some features (and endpoints) are only enabled with a higher license and define a list of required `capabilities` detailed below as `TheHive-capabilities`. To see which capabilities your license include, see the `/api/v1/status` endpoint.  ### Organisation  By default, the context of the API calls will be the default organisation of the user. If you want to target another organisation you can use the header `X-Organisation`.  With curl: ``` curl -u <user>:<password> -H 'X-Organisation: myOrg' http://localhost:9000/api/v1/alert ... ```  With python requests: ```python headers = {'X-Organisation': 'myOrg'} requests.post('http://localhost:9000/api/v1/alert', headers=headers, json=...) ``` 

API version: v1-5.5.10-1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thehive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InputCreateProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputCreateProfile{}

// InputCreateProfile struct for InputCreateProfile
type InputCreateProfile struct {
	Name string `json:"name"`
	Permissions []string `json:"permissions,omitempty"`
}

type _InputCreateProfile InputCreateProfile

// NewInputCreateProfile instantiates a new InputCreateProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputCreateProfile(name string) *InputCreateProfile {
	this := InputCreateProfile{}
	this.Name = name
	return &this
}

// NewInputCreateProfileWithDefaults instantiates a new InputCreateProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputCreateProfileWithDefaults() *InputCreateProfile {
	this := InputCreateProfile{}
	return &this
}

// GetName returns the Name field value
func (o *InputCreateProfile) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InputCreateProfile) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InputCreateProfile) SetName(v string) {
	o.Name = v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *InputCreateProfile) GetPermissions() []string {
	if o == nil || IsNil(o.Permissions) {
		var ret []string
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputCreateProfile) GetPermissionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *InputCreateProfile) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []string and assigns it to the Permissions field.
func (o *InputCreateProfile) SetPermissions(v []string) {
	o.Permissions = v
}

func (o InputCreateProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputCreateProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	return toSerialize, nil
}

func (o *InputCreateProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputCreateProfile := _InputCreateProfile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputCreateProfile)

	if err != nil {
		return err
	}

	*o = InputCreateProfile(varInputCreateProfile)

	return err
}

type NullableInputCreateProfile struct {
	value *InputCreateProfile
	isSet bool
}

func (v NullableInputCreateProfile) Get() *InputCreateProfile {
	return v.value
}

func (v *NullableInputCreateProfile) Set(val *InputCreateProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableInputCreateProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableInputCreateProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputCreateProfile(val *InputCreateProfile) *NullableInputCreateProfile {
	return &NullableInputCreateProfile{value: val, isSet: true}
}

func (v NullableInputCreateProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputCreateProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


