/*
TheHive

Testing TTPAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package thehive

import (
	"context"
	openapiclient "github.com/StrangeBeeCorp/thehive4go/thehive"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_thehive_TTPAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TTPAPIService CreateProcedureForAlert", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var alertId string

		resp, httpRes, err := apiClient.TTPAPI.CreateProcedureForAlert(context.Background(), alertId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TTPAPIService CreateProcedureForCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		resp, httpRes, err := apiClient.TTPAPI.CreateProcedureForCase(context.Background(), caseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TTPAPIService CreateSeveralProceduresForAlert", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var alertId string

		resp, httpRes, err := apiClient.TTPAPI.CreateSeveralProceduresForAlert(context.Background(), alertId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TTPAPIService CreateSeveralProceduresForCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		resp, httpRes, err := apiClient.TTPAPI.CreateSeveralProceduresForCase(context.Background(), caseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TTPAPIService DeleteProcedure", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var procedureId string

		httpRes, err := apiClient.TTPAPI.DeleteProcedure(context.Background(), procedureId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TTPAPIService DeleteProceduresInBulk", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.TTPAPI.DeleteProceduresInBulk(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TTPAPIService UpdateProcedure", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var procedureId string

		httpRes, err := apiClient.TTPAPI.UpdateProcedure(context.Background(), procedureId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
