/*
TheHive

Testing MISPAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package thehive

import (
	"context"
	openapiclient "github.com/StrangeBeeCorp/thehive4go/thehive"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_thehive_MISPAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MISPAPIService ExportCaseToMISP", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string
		var mispName string

		httpRes, err := apiClient.MISPAPI.ExportCaseToMISP(context.Background(), caseId, mispName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MISPAPIService GetMISPStatus", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.MISPAPI.GetMISPStatus(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MISPAPIService ImportCaseFromMISP", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.MISPAPI.ImportCaseFromMISP(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MISPAPIService SyncWithMISPServers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.MISPAPI.SyncWithMISPServers(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
