/*
TheHive

Testing PageAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package thehive

import (
	"context"
	"testing"

	openapiclient "github.com/StrangeBeeCorp/thehive4go/thehive"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_thehive_PageAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PageAPIService CreateAPage", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.PageAPI.CreateAPage(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PageAPIService CreateAPageInACase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		resp, httpRes, err := apiClient.PageAPI.CreateAPageInACase(context.Background(), caseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PageAPIService DeleteAPage", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string

		httpRes, err := apiClient.PageAPI.DeleteAPage(context.Background(), pageId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PageAPIService DeleteAPageInACase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string
		var pageId string

		httpRes, err := apiClient.PageAPI.DeleteAPageInACase(context.Background(), caseId, pageId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PageAPIService UpdateAPage", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string

		httpRes, err := apiClient.PageAPI.UpdateAPage(context.Background(), pageId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PageAPIService UpdateAPageInACase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string
		var pageId string

		httpRes, err := apiClient.PageAPI.UpdateAPageInACase(context.Background(), caseId, pageId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
