/*
TheHive

Testing TaskAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package thehive

import (
	"context"
	openapiclient "github.com/StrangeBee/TheHive4Go/thehive"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_thehive_TaskAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TaskAPIService CreateTaskInCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		resp, httpRes, err := apiClient.TaskAPI.CreateTaskInCase(context.Background(), caseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskAPIService DeleteTask", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var taskId string

		httpRes, err := apiClient.TaskAPI.DeleteTask(context.Background(), taskId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskAPIService GetTask", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var taskId string

		resp, httpRes, err := apiClient.TaskAPI.GetTask(context.Background(), taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskAPIService SetTaskAsDoneByOrganisation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var taskId string
		var orgId string

		httpRes, err := apiClient.TaskAPI.SetTaskAsDoneByOrganisation(context.Background(), taskId, orgId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskAPIService SetTaskAsRequiredByOrganisation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var taskId string
		var orgId string

		httpRes, err := apiClient.TaskAPI.SetTaskAsRequiredByOrganisation(context.Background(), taskId, orgId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskAPIService TaskActionsRequired", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var taskId string

		resp, httpRes, err := apiClient.TaskAPI.TaskActionsRequired(context.Background(), taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskAPIService UpdateBulkOfTask", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.TaskAPI.UpdateBulkOfTask(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskAPIService UpdateTask", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var taskId string

		httpRes, err := apiClient.TaskAPI.UpdateTask(context.Background(), taskId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
