/*
TheHive

Testing CaseAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package thehive

import (
	"context"
	openapiclient "github.com/StrangeBee/TheHive4Go/thehive"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_thehive_CaseAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CaseAPIService AddAttachmentToCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		resp, httpRes, err := apiClient.CaseAPI.AddAttachmentToCase(context.Background(), caseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService AddLinkWithAnExternalURL", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		httpRes, err := apiClient.CaseAPI.AddLinkWithAnExternalURL(context.Background(), caseId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService AddLinkWithAnotherCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		httpRes, err := apiClient.CaseAPI.AddLinkWithAnotherCase(context.Background(), caseId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService ApplyCaseTemplateOnExistingCases", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.CaseAPI.ApplyCaseTemplateOnExistingCases(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService BulkUpdateCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.CaseAPI.BulkUpdateCase(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService ChangeCaseOwningOrganisation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		httpRes, err := apiClient.CaseAPI.ChangeCaseOwningOrganisation(context.Background(), caseId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService CreateCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CaseAPI.CreateCase(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService DeleteACustomField", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var cfId string

		httpRes, err := apiClient.CaseAPI.DeleteACustomField(context.Background(), cfId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService DeleteCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var idOrName string

		httpRes, err := apiClient.CaseAPI.DeleteCase(context.Background(), idOrName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService DeleteCaseAttachment", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string
		var attachmentId string

		httpRes, err := apiClient.CaseAPI.DeleteCaseAttachment(context.Background(), caseId, attachmentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService DeleteLinkWithAnAnotherCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		httpRes, err := apiClient.CaseAPI.DeleteLinkWithAnAnotherCase(context.Background(), caseId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService DeleteLinkWithAnExternalURL", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		httpRes, err := apiClient.CaseAPI.DeleteLinkWithAnExternalURL(context.Background(), caseId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService DownloadAttachmentFromCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string
		var attachmentId string

		resp, httpRes, err := apiClient.CaseAPI.DownloadAttachmentFromCase(context.Background(), caseId, attachmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService ExportCaseAsArchive", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		resp, httpRes, err := apiClient.CaseAPI.ExportCaseAsArchive(context.Background(), caseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService GetAllLinkTypes", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CaseAPI.GetAllLinkTypes(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService GetAttachmentFromCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string
		var attachmentId string

		resp, httpRes, err := apiClient.CaseAPI.GetAttachmentFromCase(context.Background(), caseId, attachmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService GetCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var idOrName string

		resp, httpRes, err := apiClient.CaseAPI.GetCase(context.Background(), idOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService GetCaseTimeline", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		resp, httpRes, err := apiClient.CaseAPI.GetCaseTimeline(context.Background(), caseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService GetSimilarCases", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		resp, httpRes, err := apiClient.CaseAPI.GetSimilarCases(context.Background(), caseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService GetSimilarObservablesBetweenACaseAndAnotherCaseOrAlert", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string
		var alertOrCaseId string

		resp, httpRes, err := apiClient.CaseAPI.GetSimilarObservablesBetweenACaseAndAnotherCaseOrAlert(context.Background(), caseId, alertOrCaseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService ImportCaseFromFile", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CaseAPI.ImportCaseFromFile(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService ManageCaseAccess", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		httpRes, err := apiClient.CaseAPI.ManageCaseAccess(context.Background(), caseId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService MergeCases", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var ids string

		resp, httpRes, err := apiClient.CaseAPI.MergeCases(context.Background(), ids).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService MergeSimilarObservablesOfThisCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string

		resp, httpRes, err := apiClient.CaseAPI.MergeSimilarObservablesOfThisCase(context.Background(), caseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService UnlinkAlertFromCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caseId string
		var alertId string

		httpRes, err := apiClient.CaseAPI.UnlinkAlertFromCase(context.Background(), caseId, alertId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CaseAPIService UpdateCase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var idOrName string

		httpRes, err := apiClient.CaseAPI.UpdateCase(context.Background(), idOrName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
