/*
TheHive

Testing EmailIntakeAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package thehive

import (
	"context"
	openapiclient "github.com/StrangeBeeCorp/thehive4go/thehive"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_thehive_EmailIntakeAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EmailIntakeAPIService AddNewConfig", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.EmailIntakeAPI.AddNewConfig(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailIntakeAPIService AvailableProviders", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.EmailIntakeAPI.AvailableProviders(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailIntakeAPIService DeleteConfig", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var configId string

		httpRes, err := apiClient.EmailIntakeAPI.DeleteConfig(context.Background(), configId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailIntakeAPIService GWSetAuthorizationCode", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.EmailIntakeAPI.GWSetAuthorizationCode(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailIntakeAPIService GetConfig", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var configId string

		resp, httpRes, err := apiClient.EmailIntakeAPI.GetConfig(context.Background(), configId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailIntakeAPIService GetConfigs", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.EmailIntakeAPI.GetConfigs(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailIntakeAPIService GetMailboxFolders", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.EmailIntakeAPI.GetMailboxFolders(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailIntakeAPIService Sync", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.EmailIntakeAPI.Sync(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailIntakeAPIService TestConfig", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.EmailIntakeAPI.TestConfig(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailIntakeAPIService UpdateConfig", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var configId string

		httpRes, err := apiClient.EmailIntakeAPI.UpdateConfig(context.Background(), configId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailIntakeAPIService UpdateConfigs", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.EmailIntakeAPI.UpdateConfigs(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
