/*
TheHive

Testing LicenseAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package thehive

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/StrangeBee/TheHive4Go/thehive"
)

func Test_thehive_LicenseAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LicenseAPIService ActivateLicense", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var licenseId string

		httpRes, err := apiClient.LicenseAPI.ActivateLicense(context.Background(), licenseId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LicenseAPIService AddLicenseAndActivate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.LicenseAPI.AddLicenseAndActivate(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LicenseAPIService GetChallenge", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.LicenseAPI.GetChallenge(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LicenseAPIService GetCurrentLicense", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.LicenseAPI.GetCurrentLicense(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LicenseAPIService GetLicense", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var licenseId string

		resp, httpRes, err := apiClient.LicenseAPI.GetLicense(context.Background(), licenseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LicenseAPIService ListAllLicenses", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.LicenseAPI.ListAllLicenses(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
