/*
TheHive

Testing DashboardAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package thehive

import (
	"context"
	"testing"

	openapiclient "github.com/StrangeBeeCorp/thehive4go/thehive"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_thehive_DashboardAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DashboardAPIService ChangeDashboardOwnership", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dashboardId string

		httpRes, err := apiClient.DashboardAPI.ChangeDashboardOwnership(context.Background(), dashboardId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DashboardAPIService CreateDashboard", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DashboardAPI.CreateDashboard(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DashboardAPIService DeleteDashboard", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dashboardId string

		httpRes, err := apiClient.DashboardAPI.DeleteDashboard(context.Background(), dashboardId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DashboardAPIService GetDashboard", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dashboardId string

		resp, httpRes, err := apiClient.DashboardAPI.GetDashboard(context.Background(), dashboardId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DashboardAPIService UpdateDashboard", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dashboardId string

		httpRes, err := apiClient.DashboardAPI.UpdateDashboard(context.Background(), dashboardId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
