/*
TheHive

Testing FunctionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package thehive

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/StrangeBee/TheHive4Go/thehive"
)

func Test_thehive_FunctionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FunctionAPIService CreateFunction", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FunctionAPI.CreateFunction(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionAPIService DeleteFunction", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var functionId string

		httpRes, err := apiClient.FunctionAPI.DeleteFunction(context.Background(), functionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionAPIService GetDocumentationForTheContextObject", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FunctionAPI.GetDocumentationForTheContextObject(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionAPIService GetFunction", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var functionId string

		resp, httpRes, err := apiClient.FunctionAPI.GetFunction(context.Background(), functionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionAPIService InvokeFunction", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var function string

		resp, httpRes, err := apiClient.FunctionAPI.InvokeFunction(context.Background(), function).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionAPIService InvokeFunctionOnAnObject", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var function string
		var objectType string
		var objectIdOrName string

		resp, httpRes, err := apiClient.FunctionAPI.InvokeFunctionOnAnObject(context.Background(), function, objectType, objectIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionAPIService TestFunction", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FunctionAPI.TestFunction(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionAPIService UpdateFunction", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var functionId string

		httpRes, err := apiClient.FunctionAPI.UpdateFunction(context.Background(), functionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
