/*
TheHive

Testing ObservableTypeAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package thehive

import (
	"context"
	"testing"

	openapiclient "github.com/StrangeBeeCorp/thehive4go/thehive"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_thehive_ObservableTypeAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ObservableTypeAPIService CreateObservableType", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ObservableTypeAPI.CreateObservableType(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ObservableTypeAPIService DeleteObservableType", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var typeId string

		httpRes, err := apiClient.ObservableTypeAPI.DeleteObservableType(context.Background(), typeId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ObservableTypeAPIService GetObservableType", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var typeId string

		resp, httpRes, err := apiClient.ObservableTypeAPI.GetObservableType(context.Background(), typeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
