/*
TheHive

Testing AlertAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package thehive

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/StrangeBeeCorp/thehive4go/thehive"
)

func Test_thehive_AlertAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AlertAPIService AddAlertAttachment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alertId string

		resp, httpRes, err := apiClient.AlertAPI.AddAlertAttachment(context.Background(), alertId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService BulkUpdateAlert", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.AlertAPI.BulkUpdateAlert(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService CreateAlert", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AlertAPI.CreateAlert(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService CreateCaseFromAlert", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alertId string

		resp, httpRes, err := apiClient.AlertAPI.CreateCaseFromAlert(context.Background(), alertId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService DeleteAlert", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alertId string

		httpRes, err := apiClient.AlertAPI.DeleteAlert(context.Background(), alertId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService DeleteAlertAttachment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alertId string
		var attachmentId string

		httpRes, err := apiClient.AlertAPI.DeleteAlertAttachment(context.Background(), alertId, attachmentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService DeleteAlertInBulk", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.AlertAPI.DeleteAlertInBulk(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService DownloadAlertAttachment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alertId string
		var attachmentId string

		resp, httpRes, err := apiClient.AlertAPI.DownloadAlertAttachment(context.Background(), alertId, attachmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService FollowAlert", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alertId string

		httpRes, err := apiClient.AlertAPI.FollowAlert(context.Background(), alertId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService GetAlert", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alertId string

		resp, httpRes, err := apiClient.AlertAPI.GetAlert(context.Background(), alertId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService GetAlertAttachment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alertId string
		var attachmentId string

		resp, httpRes, err := apiClient.AlertAPI.GetAlertAttachment(context.Background(), alertId, attachmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService GetSimilarObservablesBetweenAlertAndAnotherAlertOrCase", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alertId string
		var alertOrCaseId string

		resp, httpRes, err := apiClient.AlertAPI.GetSimilarObservablesBetweenAlertAndAnotherAlertOrCase(context.Background(), alertId, alertOrCaseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService ImportAlertObservablesAndProceduresInCase", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alertId string
		var caseId string

		resp, httpRes, err := apiClient.AlertAPI.ImportAlertObservablesAndProceduresInCase(context.Background(), alertId, caseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService MergeAlertWithCase", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alertId string
		var caseId string

		resp, httpRes, err := apiClient.AlertAPI.MergeAlertWithCase(context.Background(), alertId, caseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService MergeBulkAlertsWithCase", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AlertAPI.MergeBulkAlertsWithCase(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService UnfollowAlert", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alertId string

		httpRes, err := apiClient.AlertAPI.UnfollowAlert(context.Background(), alertId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertAPIService UpdateAlert", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alertId string

		httpRes, err := apiClient.AlertAPI.UpdateAlert(context.Background(), alertId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
